.ci/deps.sh, bears/haskell/HaskellLintBear.py, bears/tests/haskell/HaskellLintBearTest.py, circle.yml
Fixes https://github.com/coala-analyzer/coala/issues/1565
=> bears: Add HaskellLintBear

README.rst
Fixes https://github.com/coala-analyzer/coala-bears/issues/55
=> README.rst: Add readme

bears/yaml/YAMLLintBear.py, requirements.txt, tests/yaml/YAMLLintBearTest.py, tests/yaml/config.yml
Fixes: https://github.com/coala-analyzer/coala-bears/issues/60
=> bears/yaml: Add bear for YAML using yamllint

bears/general/InvalidLinkBear.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/59
=> InvalidLinkBear: Print invalid URLs to stdout

bears/xml/XMLBear.py, requirements.txt, tests/xml/XMLBearTest.py
check for XML syntax errors using xmllint
Fixes https://github.com/coala-analyzer/coala-bears/issues/32
=> bears/xml: Add XMLBear

.ci/deps.sh, bears/dart/DartLintBear.py, circle.yml, tests/dart/DartLintBearTest.py
Add a bear for Dart, which is a scalable programming language.
It looks a bit like a python or javascript.
Fixes https://github.com/coala-analyzer/coala-bears/issues/105
=> bears/dart: Add bear for Dart using Dart Linter

bears/CheckPrerequisites.py, bears/java/CheckstyleBear.py, bears/scala/ScalaLintBear.py, bears/scala/scalastyle_config.xml, setup.py, tests/CheckPrerequisitesTest.py, tests/scala/ScalaLintBearTest.py, tests/scala/test_files/scala_config.xml
Fixes: https://github.com/coala-analyzer/coala-bears/issues/64
=> bears/scala: Add bear for scala using scalastyle

bears/c_languages/CPPCleanBear.py, requirements.txt, tests/c_languages/CPPCleanBearTest.py
Check c++ code using `cppclean`
Fixes https://github.com/coala-analyzer/coala-bears/issues/121
=> bears/c_languages: Add CPPCleanBear

.ci/deps.osx.sh, .ci/deps.sh, bears/julia/JuliaLintBear.py, setup.cfg, tests/LocalBearTestHelper.py, tests/julia/JuliaLintBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/23
=> bears: Add JuliaLintBear

bears/xml/XMLBear.py, tests/xml/XMLBearTest.py
XMLBear now will yield results from stdout as well as stderr
to report syntax errors
Fixes https://github.com/coala-analyzer/coala-bears/issues/112
=> XMLBear: Yield results from stderr

setup.cfg
This reverts commit b146a2aac75322ae94e447f82478ca01729e1580.
=> Revert "tests: Decrease timeout"

README.rst
Fixes https://github.com/coala-analyzer/coala-bears/issues/125
=> README: Use pip3 instead of pip

.gitignore
Fixes https://github.com/coala-analyzer/coala-bears/issues/94
=> .gitignore : add .swp to gitignore

Gemfile, bears/scss/SCSSLintBear.py, tests/scss/SCSSLintBearTest.py
Integrated SCSS Linter Bear
Fixes https://github.com/coala-analyzer/coala-bears/issues/141
=> bears/scss: Add SCSSLinterBear

.ci/deps.shellcheck.sh, bears/shell/ShellCheckBear.py, circle.yml, tests/shell/ShellCheckBearTest.py
The ShellCheckBear uses `shellcheck` to parse the file and returns
the issues suggested by the linter.
Fixes https://github.com/coala-analyzer/coala-bears/issues/20
=> bears/bash: Add ShellCheckBear

bears/bootstrap/BootLintBear.py, package.json, tests/bootstrap/BootLintBearTest.py
Integrated Bootstrap Linter Bear
Fixes https://github.com/coala-analyzer/coala-bears/issues/143
=> bears/bootstrap: Add BootLintBear

.ci/deps.sh, bears/lua/LuaLintBear.py, tests/lua/LuaLintBearTest.py
Adds a Linter Bear for Lua
Fixes https://github.com/coala-analyzer/coala-bears/issues/138
=> Add LuaLintBear

bears/cmake/CMakeLintBear.py, requirements.txt, tests/cmake/CMakeLintBearTest.py, tests/cmake/test_files/cmake_config.txt
Fixes https://github.com/coala-analyzer/coala-bears/issues/127
=> bears/cmake: Add CMakeLintBear

requirements.txt, tests/general/InvalidLinkBearTest.py
=> Mock Tests for InvalidLinkBear 

README.rst
Fixes https://github.com/coala-analyzer/coala-bears/issues/88
=> README: Show correct appveyor badge

bears/r/FormatRBear.py, tests/r/FormatRBearTest.py
This bear uses http://yihui.name/formatR/ to
autocorrect R code
Fixes https://github.com/coala-analyzer/coala-bears/issues/118
=> bears/r: Add formatRLintBear

RELEASE_NOTES.rst
=> Add Release Notes

requirements.txt
coala-bears should not break randomly when we change coala's API.
=> requirements: Fix coala version

.ci/deps.sh
Solves https://github.com/coala-analyzer/coala-bears/issues/170
=> Move Lua to the deps in .ci/deps.sh.

bears/typescript/TSLintBear.py, package.json, tests/typescript/TSLintBearTest.py, tests/typescript/test_files/tslint.json
Fixes https://github.com/coala-analyzer/coala-bears/issues/201
=> bears/typescript: Add TSLintBear

.ci/deps.sh, bears/java/InferBear.py, circle.yml, tests/java/InferBearTest.py
Adds an InferBear for Java
Fixes https://github.com/coala-analyzer/coala-bears/issues/30
NOTE: My previous PR had some problems with solving conflicts. I've closed that and opened a new one.
=> bears/java: Add InferBear

bears/js/JSComplexityBear.py, package.json, tests/js/JSComplexityBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/231
=> bears/js: Add JSComplexityBear

bears/xml/XMLBear.py, requirements.txt, tests/xml/XMLBearTest.py, tests/xml/test_files/concept-invalid.xml, tests/xml/test_files/concept-valid.xml, tests/xml/test_files/dtd-error.xml, tests/xml/test_files/note.dtd, tests/xml/test_files/note.xml, tests/xml/test_files/note.xsd, tests/xml/test_files/xsd-error.xml
Added schema and dtdvalid args to the XMLBear.
Also added tests related to the same.
Fixes https://github.com/coala-analyzer/coala-bears/issues/212
=> XMLBear: Add args

bears/vimscript/VintBear.py, requirements.txt, tests/vimscript/VintBearTest.py
VintBear checks the vim scripting language.
Fixes https://github.com/coala-analyzer/coala-bears/issues/252
=> Add VintBear

bears/vcs/git/GitCommitBear.py, tests/vcs/git/GitCommitBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/267
=> GitCommitBear: Improve shortlog message

.ci/deps.sh, bears/go/GoTypeBear.py, tests/go/GoTypeBearTest.py
This bear uses gotype to analyze Go code.
Fixes https://github.com/coala-analyzer/coala-bears/issues/275
=> bears/go: Add GoTypeBear

README.rst
The paragraphs are now moved a little, titles
are shown with '-' instead of '='.
Idea started by @cw1
=> README: Update on fluency

bears/python/PyDocStyleBear.py, tests/python/PyDocStyleBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/261
=> PyDocStyleBear: Add args for PyDocStyleBear

bears/vcs/git/GitCommitBear.py, tests/vcs/git/GitCommitBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/365
=> GitCommitBear: Add wip check

README.rst
The wiki page changed and the link needs to be updated
or else it does not work.
=> README.rst: Fix broken link

bears/general/InvalidLinkBear.py, tests/general/InvalidLinkBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/405
=> InvalidLinkBear: Ignore double quotes at end

.ci/deps.sh, bears/verilog/VerilogLintBear.py, tests/verilog/VerilogLintBearTest.py
This bear uses verilator to analyze and fix Verilog code
Fixes https://github.com/coala-analyzer/coala-bears/issues/400
=> bears/verilog: Add VerilogLintBear

.ci/deps.sh, bears/swift/TailorBear.py, circle.yml, tests/swift/TailorBearTest.py, tests/swift/test_files/tailor.yml
Fixes https://github.com/coala-analyzer/coala-bears/issues/11
=> bears/swift: Add TailorBear

requirements.txt
=> upgrade coala

bears/java/CheckstyleBear.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/450
=> CheckstyleBear: Handle column field correctly

bears/c_languages/codeclone_detection/CountVector.py, requirements.txt
Decorators are now in the coala_decorators module
and need to be imported correctly.
=> Decorators: Use the package

.ci/deps.sh, bears/c_languages/CPPCheckBear.py, tests/c_languages/CPPCheckBearTest.py
References https://github.com/coala-analyzer/coala-bears/issues/389
=> c_languages: Add CPPCheckBear

.ci/deps.sh, bears/yml/RAMLLintBear.py, package.json, tests/yml/RAMLLintBearTest.py
Adds RAMLLintBear which ensures consistency and
quality of code.
Fixes https://github.com/coala-analyzer/coala-bears/issues/452
=> RAMLLintBear: Add it

Gemfile, bears/ruby/RubySmellBear.py, tests/ruby/RubySmellBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/430
=> ruby: Add RubySmellBear

bears/perl/PerlCriticBear.py
The PerlCriticBear now uses the latest API, and has
its regex fixed to catch errors more accurately.
Fixes https://github.com/coala-analyzer/coala-bears/issues/404
=> PerlCriticBear: Adapt to linter v2 API

bears/general/InvalidLinkBear.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/490
=> InvalidLinkBear: Add warning about visiting URLs

README.rst
Fixes https://github.com/coala-analyzer/coala-bears/issues/387
=> README: Fix capitalization

.ci/deps.sh, Gemfile, bears/r/FormatRBear.py, tests/r/FormatRBearTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/376
=> FormatRBear: Add configs to tidy_source

bears/c_languages/CPPCleanBear.py, bears/c_languages/CPPLintBear.py, bears/cmake/CMakeLintBear.py, bears/general/InvalidLinkBear.py, bears/hypertext/HTMLLintBear.py, bears/natural_language/ProseLintBear.py, bears/python/PEP8Bear.py, bears/python/PyCommentedCodeBear.py, bears/python/PyDocStyleBear.py, bears/python/PyImportSortBear.py, bears/python/PyLintBear.py, bears/python/PyUnusedCodeBear.py, bears/python/RadonBear.py, bears/rest/reSTLintBear.py, bears/vcs/git/GitCommitBear.py, bears/vimscript/VintBear.py, bears/yml/YAMLLintBear.py
Adds REQUIREMENTS for all bears which contain
dependencies installable by ``pip``.
=> bears: Add REQUIREMENTS

bears/c_languages/GNUIndentBear.py, tests/c_languages/GNUIndentBearTest.py
Closes https://github.com/coala-analyzer/coala-bears/issues/373
=> GNUIndent: Add more configs

bears/c_languages/ClangBear.py, bears/c_languages/ClangComplexityBear.py, bears/c_languages/codeclone_detection/ClangASTPrintBear.py, bears/c_languages/codeclone_detection/ClangCloneDetectionBear.py, bears/c_languages/codeclone_detection/ClangFunctionDifferenceBear.py, bears/general/IndentationBear.py, bears/julia/JuliaLintBear.py, bears/natural_language/LanguageToolBear.py, bears/ruby/RuboCopBear.py
Some requirements were not understood and were
not added to the bear attribute.
=> bears: Add missing pip requirements

bears/r/FormatRBear.py
Closes https://github.com/coala-analyzer/coala-bears/issues/514
=> FormatRBear:  Cleanup R-command 

bears/c_languages/ClangComplexityBear.py
See https://github.com/coala-analyzer/coala/pull/2337#discussion_r69554434
=> ClangComplexityBear: Make external attribs private

bears/go/GoErrCheckBear.py, bears/java/InferBear.py, bears/natural_language/AlexBear.py, bears/r/RLintBear.py
Related to https://github.com/coala-analyzer/coala/issues/2071
=> Remove unused named capturing groups

bears/c_languages/codeclone_detection/CountVector.py, requirements.txt
The module was moved to coala_utils and is installed
by installing coala.
=> requirements.txt: Remove coala_decorators

bears/python/YapfBear.py, requirements.txt, tests/python/YapfBearTest.py
Closes https://github.com/coala-analyzer/coala-bears/issues/568
=> Add YapfBear and unify settings names

bears/coffee_script/CoffeeLintBear.py, bears/css/CSSLintBear.py, bears/dart/DartLintBear.py, bears/general/LineCountBear.py, bears/general/LineLengthBear.py, bears/haskell/HaskellLintBear.py, bears/java/JavaPMDBear.py, bears/julia/JuliaLintBear.py, bears/perl/PerlCriticBear.py, bears/python/PyImportSortBear.py, bears/scss/SCSSLintBear.py, bears/verilog/VerilogLintBear.py, tests/coffee_script/CoffeeLintBearTest.py
Closes https://github.com/coala-analyzer/coala-bears/issues/516
=> CoffeeLintBear: Make coffee_lint configurable

bears/c_languages/ClangComplexityBear.py, bears/js/JSHintBear.py, bears/js/JSONFormatBear.py, bears/natural_language/LanguageToolBear.py, bears/ruby/RuboCopBear.py, bears/ruby/RubySmellBear.py, tests/js/JSHintBearTest.py, tests/js/JSONFormatBearTest.py, tests/natural_language/LanguageToolBearTest.py, tests/ruby/RuboCopBearTest.py
related to https://github.com/coala-analyzer/coala-bears/issues/460
=> Unify settings names 

bears/natural_language/WriteGoodLintBear.py, package.json, tests/natural_language/WriteGoodLintBearTest.py
This bear uses write-good to lint
english proses.
Closes https://github.com/coala-analyzer/coala-bears/issues/573
=> bears/naturallanguage: Add WriteGoodLintBear

README.rst
Closes https://github.com/coala-analyzer/coala-bears/issues/610
=> README: Refactor

bears/general/coalaBear.py, tests/general/coalaBearTest.py
Closes https://github.com/coala-analyzer/coala-bears/issues/600
=> Add coalaBear

bears/general/AnnotationBear.py, bears/general/IndentationBear.py, tests/general/AnnotationBearTest.py, tests/general/IndentationBearTest.py
The earlier algorithm was flawed, and hence new algorithms
introduced, this doesn't break anything and even brings in a new
feature where single line strings cannot be extended to multiple
lines.
=> AnnotationBear: Refactor AnnotationBear

bears/coffee_script/CoffeeLintBear.py, bears/js/JSHintBear.py, tests/coffee_script/CoffeeLintBearTest.py, tests/js/JSHintBearTest.py
related to https://github.com/coala-analyzer/coala-bears/issues/460
=> Unify settings names

bears/js/JSHintBear.py, bears/ruby/RubySmellBear.py, tests/js/JSHintBearTest.py
related to https://github.com/coala-analyzer/coala-bears/issues/460
=> Unify setings names 

tests/generate_packageTest.py
Refactor clean-up prior to fixing https://github.com/coala-analyzer/coala-bears/issues/597
=> generate_packageTest: Patch sys.argv

bears/general/InvalidLinkBear.py, tests/general/InvalidLinkBearTest.py
Related: https://github.com/coala-analyzer/coala-bears/issues/691
=> InvalidLinkBear: Ignore templated URLs

bears/generate_package.py, tests/generate_packageTest.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/597
=> generate_package: Test version variable

bears/generate_package.py
Generates ``requirements.txt`` for those bears
that have ``PipRequirements``.
=> generate_package: Generate ``requirements.txt``

bears/generate_package.py, bears/setup.py.in
Also makes the pip requirements install upon
package installation, using setuptools.
=> generate_package: Add manifest for requirements.txt

bears/c_languages/CSecurityBear.py
Fixes https://github.com/coala-analyzer/coala-bears/issues/587
=> CSecurityBear: Fix typo

bears/general/CPDBear.py
This was identified as an issue during usability testing.
=> CPDBear: Improve error message

setup.cfg, tests/LocalBearTestHelper.py, tests/python/PyDocStyleBearTest.py
Fixes https://github.com/coala/coala-bears/issues/852
=> WIP:- Fix master

.ci/deps.sh, .coafile
=> Add CI space consistency check

bears/configfiles/PuppetLintBear.py, bears/natural_language/SpellCheckBear.py
added an asciinema recording to PuppetLintBear.py as mentioned in the issue #784  and SpellCheckBear.py as mentioned in the issue #785  .
=> Add asciinema to PuppetLintBear and SpellCheckBear

bears/__init__.py
Fixes: https://github.com/coala/coala-bears/issues/85
=> __init.py__: Added description of bears/coala-bears.

.coafile, bears/general/KeywordBear.py, tests/general/KeywordBearTest.py
Coala now ask us if we want to remove TODO notes.
See also https://github.com/coala/coala-bears/pull/778
=> KeywordBear: Remove TODO

bears/python/YapfBear.py
Closes #895 
Please check it out and let me know if this works 😸 
This is the first asciinema that I made 🎉 
Thanks!
=> Added asciinema demonstrating how to use yapfbear

bears/general/FilenameBear.py, tests/general/FilenameBearTest.py
Add ``spacecase`` convention for Bear to recognize it
Closes https://github.com/coala/coala-bears/issues/556
=> FilenameBear.py: Add ``spacecase`` convention

.ci/deps.sh, bears/python/MypyBear.py, requirements.txt, tests/python/MypyBearTest.py
Add a bear that runs mypy, a checker for PEP 484 type hints.
Closes https://github.com/coala-analyzer/coala-bears/issues/601
=> Add MypyBear

bears/python/MypyBear.py
I noticed it was missing when doing the tweet.
=> MypyBear: Add ASCIINEMA_URL

tests/natural_language/LanguageToolBearTest.py
Fix for #25.
Also fixes grammar error in original English sentence.
=> Fix German (+ English) sample in LanguageToolBearTest

Gemfile, bears/csv/CsvLintBear.py, tests/csv/CsvLintBearTest.py
Closes https://github.com/coala/coala-bears/issues/927
=> Bears: Add CsvLintBear

bears/general/KeywordBear.py
Closes https://github.com/coala/coala-bears/issues/819
=> KeywordBear: Make ``todo`` and ``fixme`` default

bears/csv/CSVLintBear.py, tests/csv/CSVLintBearTest.py
Closes https://github.com/coala/coala-bears/issues/955
=> CSVLintBear: Rename CsvLintBear

.coafile, bears/python/BanditBear.py, requirements.txt, setup.cfg, tests/python/BanditBearTest.py, tests/python/bandit_test_files/assert.py, tests/python/bandit_test_files/exec-py2.py, tests/python/bandit_test_files/good_file.py, tests/python/bandit_test_files/httpoxy_cgihandler.py, tests/python/bandit_test_files/jinja2_templating.py, tests/python/bandit_test_files/skip.py
Python source code security analysis.
=> Add BanditBear

bears/jinja2/Jinja2Bear.py, tests/jinja2/Jinja2BearTest.py
This Bear is a native Bear which processes [Jinja2](http://jinja.pocoo.org/docs/dev/) template files.
There is no real global style guide for Jinja2. The one by the [Chromium Project](https://www.chromium.org/developers/jinja), which I referenced in the proposal, turned out to be ~~crap~~ suboptimal, because in many cases it collides with the official documentation and as a heavy user of Jinja2 I just don't like it.
So I chose the defaults of this Bear by looking at the official documentation, my own code and other sources on the Web, I also made it configurable, so that even the Chromium folks could still use it.
The bear can now detect:
* **Unmatched opening or closing control blocks:**  In Jinja2 each `if` and `for` construct must be matched by a corresponding closing tag. If this is …
=> New Bear: Jinja2Bear

bears/java/JavaPMDBear.py, tests/general/InvalidLinkBearTest.py
The binary differs. The very same change was already apploed to the
CPDBear but people often forget this one.
Fixes https://github.com/coala/coala-bears/issues/998
=> JavaPMDBear: Add Mac support

bears/python/PyUnusedCodeBear.py
Re-indent autoflake.fix_code invocation according to pep8,
after @sils sugestion.
Closes https://github.com/coala/coala-bears/issues/1015
=> PyUnusedCodeBear: Re-indent autoflake.fix_code

RELEASE_NOTES.rst
Fixes https://github.com/coala/coala-bears/issues/1048
=> swift: Add __init__.py

bears/python/YapfBear.py, bears/vcs/git/GitCommitBear.py, tests/cmake/CMakeLintBearTest.py, tests/js/JSHintBearTest.py, tests/python/MypyBearTest.py, tests/scala/ScalaLintBearTest.py, tests/yml/YAMLLintBearTest.py
ContextManagers.py from coalib has been removed
using coala_utils one instead.
=> Use ContextManagers.py from coala_utils

bears/general/InvalidLinkBear.py
Document complex regex using ``re.X`` mode
Closes https://github.com/coala/coala-bears/issues/1018
=> InvalidLinkBear.py: Document regex in Verbose

bears/python/PyFlakesBear.py, requirements.txt, tests/python/PyFlakesBearTest.py
Closes https://github.com/coala/coala-bears/issues/825
=> bears/python: Add PyFlakesBear

bears/js/JSONFormatBear.py
=> GCI: Update JSONFormatBear.py 

bears/natural_language/SpellCheckBear.py
SpellCheckBear.py:	Added Documentation
The documentation advertises the application of this Bear
Fixes https://github.com/coala/coala-bears/issues/1047
=> SpellCheckBear.py: Added Documentation

bears/go/GofmtBear.py
It's nice to see how the bear works and see it in action. Therefore,
it's a good idea to have a demo for this bear.
This commit demostrate GofmtBear by using a sample that has a couple
of "classic" formatting issues such as mixed indentation and semi
colons.
=> Fix #1081 - Add Asciinema for GofmtBear

bears/python/PythonPackageInitBear.py, tests/python/PythonPackageInitBearTest.py
Closes https://github.com/coala/coala-bears/issues/1051
=> PythonPackageInitBear: Detect directories with missing init file

.ci/deps.sh
dbus is no longer used by coala.
Closes https://github.com/coala/coala/issues/2949
=> CircleCI: Remove installation of dbus

.ci/deps.sh
=> deps.sh: Remove 'gi' Python dependencies

.coafile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coala/coala-bears/1091)
=> .coafile: Enable PythonPackageInitBear

bears/natural_language/ProseLintBear.py
Closes https://github.com/coala/coala-bears/issues/1139 and removes ProseLintBear from the list at https://github.com/coala/coala-bears/issues/1136
Reviewer: @userzimmermann
=> ProseLintBear: Add English only and link to doc

README.rst
Fixes https://github.com/coala/coala-bears/issues/1157
=> README.rst: Update link for cib usage instruction

bears/setup.py.in
=> setup.py.in: Modify quotes

README.rst
Fixes https://github.com/coala/coala-bears/issues/1159
=> README.rst: Update broken links

bears/general/InvalidLinkBear.py, tests/general/InvalidLinkBearTest.py
Allow variable timeouts for servers that are slow in responding, and
hence increase the accuracy of the number of invalid links reported by
coala.
Closes https://github.com/coala/coala-bears/issues/686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coala/coala-bears/877)
=> InvalidLinkBear: Allow variable timeouts

.coafile
Updates ineffective 47f61cc7
Closes https://github.com/coala/coala-bears/issues/1177
=> .coafile: Enable reSTLintBear on README.rst

bears/natural_language/LanguageToolBear.py, bears/python/MypyBear.py, bears/python/YapfBear.py, bears/vcs/git/GitCommitBear.py
./bears/python/MypyBear.py
./bears/python/YapfBear.py
./bears/vcs/git/GitCommitBear.py
./bears/natural_language/LanguageToolBear.py
=> Removes unused imports in bears

tests/java/CheckstyleBearTest.py
Check the AssertionError exception message.
Addresses https://github.com/coala/coala-bears/issues/1194
=> CheckstyleBearTest: Use assertRaisesRegex

.ci/generate_bear_requirements.py
generate_requirements_bears.py is a script for generating a pip
requirements text file for linters that can be installed with pip
Closes https://github.com/coala/coala-bears/issues/1044
=> CI: Add script to generate `bear-requirements.txt`

.ci/deps.sh, .travis.yml
Adds:
- flawfinder
- libperl-critic-perl
=> TravisCI: Add new packages in Travis whitelist

.travis.yml, requirements.txt, setup.py
Depends on https://github.com/coala/coala/pull/3384
=> setup.py: Delegate Python version check to coala

setup.cfg
Fixes https://github.com/coala/coala/issues/3383
=> setup.cfg: Build wheel for Python 3.4-3.6 only

.ci/deps.sh
Add php-codesniffer which is part of the precise image.
Manually include ocaml and camlp4, which are automatically included
by opam with `ppa:avsm/ppa`.
lintr requires g++ and gfortran >= 4.9.
v5 is already installed by using xenial, so this is activated.
Closes https://github.com/coala/coala-bears/issues/829
=> CircleCI: Fix Trusty builds

.coafile, bears/csv/CSVLintBear.py, bears/java/CheckstyleBear.py, bears/natural_language/WriteGoodLintBear.py, bears/python/PyImportSortBear.py, bears/ruby/RuboCopBear.py, bears/scss/SCSSLintBear.py, bears/setup.py.in, tests/general/AnnotationBearTest.py, tests/jinja2/Jinja2BearTest.py, tests/natural_language/WriteGoodLintBearTest.py, tests/python/BanditBearTest.py
Add PycodestyleBear in the autopep8 section
of coafile.
Closes https://github.com/coala/coala-bears/issues/1122
=> .coafile: add PycodestyleBear

.travis.yml
Removed apt package which set java version to 9.
=> Try to fix master

bear-requirements.txt, bears/gettext/DennisBear.py, tests/gettext/DennisBearTest.py, tests/gettext/test_files/dennis_invalid_test.po, tests/gettext/test_files/dennis_valid_test.po
Linter bear for translated PO and POT files.
Closes https://github.com/coala/coala-bears/issues/892
=> bears/gettext: Add DennisBear

bears/jinja2/Jinja2Bear.py
Related to https://github.com/coala/coala/issues/3488
=> Jinja2Bear: Improve documentation

requirements.txt
Coala had a release with a fix in dependency_management,
so changed version to 0.10.0.dev20170113094654
=> requirements.txt: Fixed coala version

bears/general/KeywordBear.py
Propose patches to the user for all the keywords found
in the file.
Fixes https://github.com/coala/coala-bears/issues/1274
=> KeywordBear: Propose patches for all todos

tests/general/KeywordBearTest.py
Closes https://github.com/coala/coala-bears/issues/1314
=> KeywordBearTest.py: Named arguments replaced with named keywords

.ci/Gemfile.jinja2, .ci/generate_bear_requirements.py, .ci/package.json.jinja2, .travis.yml, Gemfile, bears/js/ESLintBear.py, bears/markdown/MarkdownBear.py, bears/scss/SCSSLintBear.py, bears/typescript/TSLintBear.py, package.json
Related to the issue https://github.com/coala/coala-bears/issues/1257 and #1258
=> Generate package.json and Gemfile

bear-requirements.txt, bears/python/PyromaBear.py, setup.cfg, tests/python/PyromaBearTest.py, tests/python/pyroma_test_files/complete/complete/__init__.py, tests/python/pyroma_test_files/complete/complete/tests.py, tests/python/pyroma_test_files/complete/setup.cfg, tests/python/pyroma_test_files/complete/setup.py, tests/python/pyroma_test_files/minimal/setup.py
Add PyromaBear for checking Python packaging
best practices.
Closes https://github.com/coala/coala-bears/issues/792
=> PyromaBear: Add PyromaBear

bears/general/InvalidLinkBear.py, tests/general/InvalidLinkBearTest.py
Closes https://github.com/coala/coala-bears/issues/1244
=> InvalidLinkBear: Deprecate timeout setting

bears/css/StyleLintBear.py, package.json, tests/css/StyleLintBearTest.py, tests/css/test_files/stylelint_bad.css, tests/css/test_files/stylelint_good.css
StyleLintBear is a bear which uses stylelint to lint css files.
Closes https://github.com/coala/coala-bears/issues/1255
=> Add StyleLintBear

bears/js/JSHintBear.py
Fixes https://github.com/coala/coala-bears/issues/1372
=> JSHintBear: Remove bare except

RELEASE_NOTES.rst
Changing 'coala-analyzer' to 'coala'
Closes https://github.com/coala/coala-bears/issues/1382
=> RELEASE_NOTES.rst: Update URL references

.ci/appveyor.yml
Replaces five pip commands performing custom caching
with one command which uses pip's inbuilt caching.
=> AppveyorCI: Use pip caching

bears/general/IndentationBear.py
Fix typo whith -> with on line 260.
Fixes https://github.com/coala/coala-bears/issues/1440
them. …
=> IndentationBear: Fix typo

MANIFEST.in
bear-requirements.txt is used by setup.py and
requirements.txt
Fixes https://github.com/coala/coala-bears/issues/1448
(cherry-picked from b42a56b)
them. …
=> MANIFEST.in: Add bear-requirements.txt

bear-requirements.txt, bears/rest/reSTLintBear.py
Closes https://github.com/coala/coala-bears/issues/1452
them.
instead. …
=> Upgrade restructuredtext-lint to 1.0

bear-requirements.txt, bears/yaml/YAMLLintBear.py
Closes https://github.com/coala/coala-bears/issues/1252
them.
instead. …
=> Upgrade yamllint to 1.6.1

bears/r/RLintBear.py
Closes https://github.com/coala/coala-bears/issues/1379
them.
instead. …
=> RLintBear.py: Add version requirement

.ci/deps.sh, .travis.yml, bears/elm/ElmLintBear.py, circle.yml, package.json, tests/elm/ElmLintBearTest.py
Closes https://github.com/coala/coala-bears/issues/1073
them.
instead. …
=> bears/elm: Add ElmLintBear

bears/general/LineCountBear.py, tests/general/LineCountBearTest.py
Add option to exclude blank lines. The setting is disabled by default.
Closes https://github.com/coala/coala-bears/issues/1478
them. …
=> LineCountBear.py: Add exclude_blank_lines option

requirements.txt
=> requirement.txt: Update coala

bears/general/FilenameBear.py, tests/general/FilenameBearTest.py
Closes https://github.com/coala/coala-bears/issues/1533
them.
instead. …
=> FilenameBear.py: Add kebabcase naming convention

.ci/Gemfile.jinja2, .ci/generate_bear_requirements.py, Gemfile, bears/configfiles/PuppetLintBear.py, bears/ruby/RuboCopBear.py
Pin to verion 0.47.1 because tests were failing due to the
launch of a new release of rubocop 0.48.0
Closes https://github.com/coala/coala-bears/issues/1548
them.
After you submit your pull request, **DO NOT click the 'Update …
=> RuboCopBear.py: Pin to version 0.47.1

.ci/Gemfile.jinja2, .ci/generate_bear_requirements.py, Gemfile, bears/c_languages/GNUIndentBear.py, bears/coffee_script/CoffeeLintBear.py, bears/configfiles/PuppetLintBear.py, bears/python/YapfBear.py, bears/r/FormatRBear.py, bears/ruby/RuboCopBear.py
Includes https://github.com/coala/coala-bears/pull/1555
Fixes https://github.com/coala/coala-bears/issues/1561 and https://github.com/coala/coala-bears/issues/1544
=> Remove triple backticks

bears/coffee_script/CoffeeLintBear.py
Restore unintentionally incorrectly removed documentation comment
`are accepted.` while fixing https://github.com/coala/coala-bears/issues/1544
and https://github.com/coala/coala-bears/issues/1561 in commit
8ccc1ea81ad1e1e7c46e85521c4684aea46b7a02
Fixes https://github.com/coala/coala-bears/issues/1544
Fixes https://github.com/coala/coala-bears/issues/1561
them.
our bot will still report the issues for …
=> Restore incorrectly removed documentation

bears/yaml/RAMLLintBear.py, package.json
Update NpmRequirement version to include a range of
versions >=1.2.2 <1.2.4 || >=1.2.5 <1.3.0 since
version 1.2.4 has been marked depreciated.
Fixes https://github.com/coala/coala-bears/issues/1470
them. …
=> RAMLLintBear.py: Update NpmRequirement version

bears/general/FilenameBear.py, tests/general/FilenameBearTest.py
Add default naming conventions that are widely accepted for
languages like java, javascript and python.
Closes https://github.com/coala/coala-bears/issues/1083
them.
After you submit your pull request, **DO NOT click the 'Update …
=> FilenameBear.py: Enable default naming convention

bears/yaml/YAMLLintBear.py, tests/yaml/YAMLLintBearTest.py
Change the severity level of the syntax errors detected from
normal to major.
Fixes https://github.com/coala/coala-bears/issues/1525
them.
When asked …
=> YAMLLintBear: Change `SEVERITY_LEVEL`

README.rst
README.rst: Update
Update the latest stable badge in readme to 0.10.0 from 0.8.0
fixes https://github.com/coala/coala-bears/issues/1408
=> Update the latest stable badge in readme to 0.10.0 from 0.8.0

.coafile, bears/Constants.py, bears/c_languages/ClangBear.py, bears/css/StyleLintBear.py, bears/perl/PerlCriticBear.py, bears/ruby/RubySyntaxBear.py, tests/css/StyleLintBearTest.py, tests/haskell/GhcModBearTest.py, tests/haskell/HaskellLintBearTest.py
Closes https://github.com/coala/coala-bears/issues/1600
them.
instead. …
=> .coafile: Activate remove_all_unused_imports

bears/hypertext/HTMLLintBear.py
Closes https://github.com/coala/coala-bears/issues/1611
them.
instead. …
=> HTMLLintBear: Add PHP and Jinja2 language tags

bears/yaml/YAMLLintBear.py, tests/yaml/YAMLLintBearTest.py
Support max_line_length setting which can be configurable.
Closes https://github.com/coala/coala-bears/issues/1614
them. …
=> YAMLLintBear: Support 'max_line_length' setting

bears/c_languages/CPPCheckBear.py, bears/c_languages/CSecurityBear.py, bears/c_languages/CSharpLintBear.py, bears/c_languages/GNUIndentBear.py, bears/general/LicenseCheckBear.py, bears/latex/LatexLintBear.py, bears/perl/PerlCriticBear.py, bears/ruby/RubySyntaxBear.py, bears/verilog/VerilogLintBear.py, bears/xml2/XMLBear.py
Upgrades REQUIREMENTS for:
- CPPCheckBear
- CSecurityBear
- CSharpLintBear
- GNUIndentBear
- LicenseCheckBear
- LatexLintBear
- PerlCriticBear
- RubySyntaxBear
- VerilogLintBear
- XMLBear
Closes https://github.com/coala/coala-bears/issues/1659
=> Upgrade DistributionRequirement

bears/lua/LuaLintBear.py
Replace ``DistributionRequirement`` with ``LuarocksRequirement``
which is now supported by ``dependency_management`` 0.4.0
Closes https://github.com/coala/coala-bears/issues/1652
them. …
=> LuaLintBear: Replace ``DistributionRequirement``

bears/r/FormatRBear.py, bears/r/RLintBear.py
=> RscriptRequirement: Remove ``flag`` and ``repo``

bears/haskell/GhcModBear.py
Closes https://github.com/coala/coala-bears/issues/1357
=> GhcModBear.py: Add DistributionRequirement

bears/shell/ShellCheckBear.py
We can find version"packages.ubuntu.com/xenial/shellcheck"
Closes:https://github.com/coala/coala-bears/issues/1359
them. …
=> ShellCheck: Add DistributionRequirement

bears/php/PHPCodeSnifferBear.py, bears/php/PHPMessDetectorBear.py
Add ComposerRequirement via AnyOneOfRequirements
to PHPCodeSnifferBear and PHPMessDetectorBear.
Closes https://github.com/coala/coala-bears/issues/1657
them. …
=> Add ComposerRequirement

tests/general/IndentationBearTest.py
Closes https://github.com/coala/coala-bears/issues/1641
them.
instead. …
=> Fix the SpaceConsistencyBear typo

bears/swift/TailorBear.py
This entrypoint change TailorBear to use REQUIREMENT as per coala core change.
Closes https://github.com/coala/coala-bears/issues/1666
them.
When …
=> TailorBear: Add DistributionRequirement

bears/vhdl/VHDLLintBear.py
Closes https://github.com/coala/coala-bears/issues/1665
them.
instead. …
=> VHDLLintBear.py: Add DistributionRequirement

.coafile, Gemfile, bears/ruby/RuboCopBear.py, requirements.txt
=> Release 0.9 fixes

.ci/deps.sh
Change the old package to new one, as it is removed
and updated to a new one.
Closes https://github.com/coala/coala-bears/issues/1488
them.
When asked …
=> GoTypeBear.py: Update the package reference

tests/general/LicenseCheckBearTest.py
Fixes #1704
them.
instead.
Please consider helping us by reviewing other …
=> LicenseCheckBearTest: Use with to close file

bears/general/IndentationBear.py
=> IndentationBears.py: Remove pragma no cover

bears/python/MypyBear.py
The reference was linked to coala-analyzer instead of coala.
Closes https://github.com/coala/coala-bears/issues/1383
them. …
=> MypyBear: Update references to coala-analyzer

requirements.txt, tests/general/InvalidLinkBearTest.py
Only one 404 should be in each test, as the mock infrastructure
means that the domain and any path are irrelevant and are not
different test scenarios, and so are not useful.
Closes https://github.com/coala/coala-bears/issues/1726
them.
pass on every single …
=> InvalidLinkBearTest: Remove some unnecesary tests

tests/css/CSSAutoPrefixBearTest.py, tests/go/GofmtBearTest.py, tests/js/HappinessLintBearTest.py, tests/python/PyFlakesBearTest.py
Add 'Test' in variable name
Closes https://github.com/coala/coala-bears/issues/1732
them. …
=> Remove shadow from bear names in test module

bears/python/PycodestyleBear.py, tests/python/PycodestyleBearTest.py
=> Pycodestyle

RELEASE_NOTES.rst
@meetmangukiya summons @Mixih - the release lead for a review
and these are the stats, go figure.
```sh
meet@phoenix ~/Desktop/ghubby/coala/coala-bears [meet/relnotes/0.11 *]
_ % git log --oneline 1096b293af15059ce363c0569d5927de2cefd9c2..master | wc                                                                                       !3862
25     131    1263
meet@phoenix ~/Desktop/ghubby/coala/coala-bears [meet/relnotes/0.11 *]
_ % git log --oneline rel/0.10.1..master | wc                                                                                                                     !3863
101     529    4884
```
I can't believe I've written release notes for 76 commits :P
=> RELEASE_NOTES.rst: Add 0.11.0 release notes

.ci/deps.sh
Fixes https://github.com/coala/coala-bears/issues/1763
=> .ci/deps.sh: Fix infer breakage

bears/go/GofmtBear.py, tests/go/GofmtBearTest.py
Adds the gofmt simplify option accessible via ‘simplify’ setting.
Also adds a test for it.
Closes https://github.com/coala/coala-bears/issues/357
them. …
=> GofmtBear: Add simplify flag

RELEASE_NOTES.rst
=> 0.11 release notes

bear-requirements.txt, bears/rest/RSTcheckBear.py
bear_requirements: changed rstcheck to version 3.1
Updated version in both of the requested files.
Closes:https://github.com/coala/coala-bears/issues/1717
them. …
=> RSTcheckBear.py: changed rstcheck to version 3.1

.ci/generate_bear_requirements.py, bear-requirements.txt, bears/apertium/ApertiumLintBear.py, tests/apertium/ApertiumLintBearTest.py, tests/apertium/test_files/apertium-ba-ad.en.dix, tests/apertium/test_files/apertium-go-od.en.dix, tests/apertium/test_files/apertium_config.json
ApertiumLintBear is a bear which uses
apertium-lint to lint 4 file types namely
dictionaries, transfer, modes and tagger.
Closes https://github.com/coala/coala-bears/issues/1320
them. …
=> Add ApertiumLintBear

tests/python/PyImportSortBearTest.py
Fixes https://github.com/coala/coala-bears/issues/1802
them.
instead. …
=> ImportSort: Replace test case import this with io

requirements.txt, tests/jinja2/Jinja2BearTest.py
=> Jinja2BearTest: Update to comply with latest coala version

.ci/generate_bear_requirements.py, package.json
Fixes https://github.com/coala/coala-bears/issues/1586
Continues https://github.com/coala/coala-bears/pull/1639
them. …
=> generator: Fix generator for json indentation

README.rst
Added a waffle.io graph showing the number of closed PRs and closed
issues in the last month.
Closes https://github.com/coala/coala-bears/issues/1792
=> README.rst: Add waffle.io graph

tests/general/InvalidLinkBearTest.py
There are many functions and methods created in InvalidLinkBear,
but the functionality of these functions and methods has been
provided by LocalBearTestHelper class, so we need to delete
the functions and methods in InvalidLinkBearTest and
using functions and methods from LocalBearTestHelper.
Closes https://github.com/coala/coala-bears/issues/1728
them.
our bot will still report the issues for the …
=> test: Convert InvalidLinkBearTest to use LocalBearTestHelper

README.rst
Fix the stable version badge from version
0.10.0 to 0.11.1
Closes https://github.com/coala/coala-bears/issues/1815
them. …
=> README.rst: Fix stable version badge

bears/python/VultureBear.py
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
of the review queue.
The more you review, the more your score will grow at coala.io and we will
review your PRs …
=> VultureBear: Add SEE_MORE attribute

bear-requirements.txt, bears/python/VultureBear.py
Refactor VultureBear to make use of the vulture API rather than using it as a 
command line tool.
Closes: https://github.com/coala/coala-bears/issues/1805
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, …
=> VultureBear: Make use of the vulture API

.travis.yml, circle.yml
=> CI: Cache Sphinx build directory

tests/general/InvalidLinkBearTest.py
Split test_run() method in InvalidLinkBearTest into several
methods.
Closes https://github.com/coala/coala-bears/issues/1725
them. …
=> InvalidLinkBearTest: Split test_run() into several methods

.ci/appveyor.yml, .coafile, .rultor.yml, .travis.yml, circle.yml
Add YAMLLintBear for fixing issues with .yml files
Fixes https://github.com/coala/coala-bears/issues/1779
them. …
=> .coafile: Add YAMLLintBear

bears/python/PyUnusedCodeBear.py
Closes https://github.com/coala/coala-bears/issues/1832
them.
instead. …
=> PyUnusedCodeBear.py: Change docstring

bears/python/VultureBear.py, tests/python/VultureBearTest.py
Report confidence values along with results in VultureBear
Closes: #1867 
them.
=> VultureBear: Report confidence values

.coafile, bears/python/PyUnusedCodeBear.py
Closes https://github.com/coala/coala-bears/issues/1824
them.
instead. …
=> PyUnusedCodeBear: Set remove_all_unused_imports

requirements.txt
=> requirements.txt: Bump coala version up

bears/xml2/XMLBear.py, tests/xml2/XMLBearTest.py, tests/xml2/test_files/note.rng, tests/xml2/test_files/rng-error.xml
Add support for RelaxNG schema for validation
Closes https://github.com/coala/coala-bears/issues/1693
=> XMLBear.py: Add RelaxNG support

tests/apertium/ApertiumLintBearTest.py, tests/c_languages/CSharpLintBearTest.py, tests/css/StyleLintBearTest.py, tests/general/FilenameBearTest.py, tests/general/SpaceConsistencyBearTest.py, tests/gettext/DennisBearTest.py, tests/go/GoVetBearTest.py, tests/haskell/GhcModBearTest.py, tests/haskell/HaskellLintBearTest.py, tests/java/CheckstyleBearTest.py, tests/php/PHPLintBearTest.py, tests/python/MypyBearTest.py, tests/python/PEP8BearTest.py, tests/python/PyCommentedCodeBearTest.py, tests/python/PyLintBearTest.py, tests/python/YapfBearTest.py, tests/python/requirements/PySafetyBearTest.py
Closes https://github.com/coala/coala-bears/issues/1729
them.
instead. …
=> Replaced check_validity(..,false) with check_invalidity(..)

bears/general/KeywordBear.py, requirements.txt, tests/general/KeywordBearTest.py
Fixes https://github.com/coala/coala-bears/issues/1885
=> KeywordBearTest: Add language setting in test

bear-requirements.txt, bears/general/InvalidLinkBear.py, bears/general/MementoBear.py, bears/general/URLBear.py, tests/general/InvalidLinkBearTest.py, tests/general/MementoBearTest.py, tests/general/URLBearTest.py
- Split some parts of InvalidLinkBear to URLBear.
Some methods and functions that related to URL finding
and status code checking are moved to URLBear.
- Assign URLBear to InvalidLinkBear's BEAR_DEPS,
so InvalidLinkBear just control the results of URLBear.
- Replace link_context from enum to use LINK_CONTEXT flags.
`link_context` that uses coalib.misc.Enum.enum() isn't pickleable.
So I replaced it by using `aenum`'s Flag.
- Change some InvalidLinkBear testcases to comply with URLBear.
- Change MementoBear to use URLBear instead of InvalidLinkBear.
- Delete MementoBear `link_ignore_list` setting, since it has been
defined in URLBear.
- Create URLBearTest.py.
Closes https://github.com/coala/coala-bears/issues/1871 …
=> InvalidLinkBear: Split some parts into URLBear

bears/julia/JuliaLintBear.py
Closes #1613
them.
instead.
Please consider helping us by reviewing other …
=> JuliaLintBear.py: Use JuliaRequirement

bears/js/JSStandardBear.py, package.json, tests/js/JSStandardBearTest.py
bears/js/JSStandardBear.py: Create JSStandardBear
package.json: Add 'standard' js linter
Add https://github.com/feross/standard
JavaScript Standard Style linter
Closes https://github.com/coala/coala-bears/issues/1753
=> Add new JSStandardBear

bears/general/FilenameBear.py, tests/general/FilenameBearTest.py
FilenameBearTest.py: Add tests
Add a new feature to the FilenameBear.
The bear can check if the filename matches a certain prefix/suffix.
Closes https://github.com/coala/coala-bears/issues/1817
them. …
=> FilenameBear.py: Add prefix/suffix matching feature

bears/natural_language/WriteGoodLintBear.py
This change fixes the confusion between words referring to standard
prose and words referring not specific technical/informative term
Closes https://github.com/coala/coala-bears/issues/1851
them.
After you submit your pull request, …
=> Change back ticks to double quotes

RELEASE_NOTES.rst
Use anonymous hyperlink references for common links like `here`.
Anonymous references are suffixed by `__` instead of `_`.
Fixes https://github.com/coala/coala-bears/issues/1046
them. …
=> RELEASE_NOTES.rst: Change to anonymous hyperlinks references

bears/r/RLintBear.py
Newcomer issue to add URL for lintr
Reference https://github.com/coala/coala/issues/1136
- [X ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [X ] I ran coala over my code locally. (*All commits have to pass
pass on every …
=> RLintBear.py: Added URL to SEE_MORE

README.rst, bears/general/KeywordBear.py, bears/scss/SCSSLintBear.py, bears/vcs/git/GitCommitBear.py, tests/vcs/git/GitCommitBearTest.py
Cherry-picked a couple of approved PRs:
https://github.com/coala/coala-bears/pull/1761
https://github.com/coala/coala-bears/pull/1852
https://github.com/coala/coala-bears/pull/1925
https://github.com/coala/coala-bears/pull/1756
https://github.com/coala/coala-bears/pull/1887
=> Cherry pick 2017 07 15

tests/markdown/MarkdownBearTest.py
Linked to PR: https://github.com/coala/coala-bears/pull/1920
Closes https://github.com/coala/coala-bears/issues/1910
them. …
=> MarkdownBearTest: Inconsistent spacing

requirements.txt
=> requirements.txt: Update coala

bears/apertium/ApertiumLintBear.py
changes 'defLabel_closed' to 'def_Label_closed'.
Closes https://github.com/coala/coala-bears/issues/1964
them. …
=> ApertiumLintBear.py: Fix typo

bear-requirements.txt, bears/general/MementoBear.py
=> Upgrade memento_client to 0.6.1 #1968

tests/haskell/GhcModBearTest.py, tests/haskell/HaskellLintBearTest.py, tests/python/MypyBearTest.py, tests/python/YapfBearTest.py
Specified changes have been made. 
Closes https://github.com/coala/coala-bears/issues/1730
them. …
=> Solved issue #1730

bear-requirements.txt, bears/python/PyUnusedCodeBear.py
~~Blocked by https://github.com/coala/coala/pull/4659~~
Closes https://github.com/coala/coala-bears/issues/2016
=> PyUnusedCodeBear: Aspectization

bears/documentation/DocumentationStyleBear.py
Now #L40 returns an instance of a
processed/fixed DocumentationComment.
Closes https://github.com/coala/coala-bears/issues/2009
them. …
=> DocumentationStyleBear: Update docstring

tests/xml2/XMLBearTest.py
Fixes https://github.com/coala/coala-bears/issues/2052 and https://github.com/coala/coala-bears/issues/2053
=> Fix XMLBearTest

tests/general/KeywordBearTest.py
Replaced assertEquals with assertEqual.
closes #2049 
them.
instead. …
=> change assertEquals to assertEqual, closes #2049

tests/js/HappinessLintBearTest.py, tests/js/JSStandardBearTest.py
New version of Happiness & JSStandard has a new rule
`no-constant-condition`
https://eslint.org/docs/rules/no-constant-condition
Related to https://github.com/coala/coala-bears/issues/872
=> tests: Modify js tests to pass new ESLint rule

bears/c_languages/codeclone_detection/ClangFunctionDifferenceBear.py
Changes single inverted commas (') to double
inverted commas(") for the docstrings.
Closes: https://github.com/coala/coala-bears/issues/1999
them. …
=> ClangFunctionDifferenceBear.py: Changes in docstrings

tests/php/PHPMessDetectorBearTest.py
Fixes #2047 
them.
instead.
Please consider helping us by reviewing other …
=> Fixes #2047: PHPMessDetectorBearTest: Closed opened test files properly

Gemfile, bears/ruby/RuboCopBear.py, tests/ruby/RuboCopBearTest.py
Closes https://github.com/coala/coala-bears/issues/2116
them.
instead. …
=> RuboCopBear : Upgrade to version 0.51.0

tests/yaml/TravisLintBearTest.py
This closes opened test files properly using a with-context
Closes #2042
=> TravisLintBearTest.py: Close opened files properly

.ci/generate_bear_requirements.py, Gemfile
=> Gemfile: Always use require: false

Gemfile, bears/haml/HAMLLintBear.py, tests/haml/HAMLLintBearTest.py, tests/haml/hamllint_test_files/.haml-lint.yml, tests/haml/hamllint_test_files/test_alignment_tabs_good_file.haml, tests/haml/hamllint_test_files/test_alt_text_bad_file.haml, tests/haml/hamllint_test_files/test_alt_text_good_file.haml, tests/haml/hamllint_test_files/test_consecutive_comments_bad_file.haml, tests/haml/hamllint_test_files/test_consecutive_comments_good_file.haml, tests/haml/hamllint_test_files/test_consecutive_comments_good_file_via_config.haml, tests/haml/hamllint_test_files/test_consecutive_silent_scripts_bad_file.haml, tests/haml/hamllint_test_files/test_consecutive_silent_scripts_good_file.haml, tests/haml/hamllint_test_files/test_no_trailing_whitespace_file.haml, tests/haml/hamllint_test_files/test_trailing_whitespace_file.haml
Runs on HAML files and
checks for style and
lint checks
Closes https://github.com/coala/coala-bears/issues/289
them. …
=> Add HAMLLintBear

bears/hypertext/HTMLLintBear.py, tests/hypertext/HTMLLintBearTest.py
Fixes issue #1741
them.
instead.
Please consider helping us by reviewing …
=> HTMLLintBear: Add `use_spaces` option

setup.py
Changed url to 'http://coala.io/' in setup.py.
closes #2135 
them. …
=> setup.py: Change url to http://coala.io/

bears/scss/SCSSLintBear.py
Fixes the spelling mistake in SCSSLintBear
by changing check_ulrs_format to
check_url_format
Fixes: https://github.com/coala/coala-bears/issues/1912
them. …
=> SCSSLintBear.py: Renamed parameter

bears/dart/DartLintBear.py
Adds DistributionRequirement in DartLintBear.py for brew package
Fixes https://github.com/coala/coala-bears/issues/1664
them. …
=> [MRG] DartLintBear.py: Add DistributionRequirement

bears/general/QuotesBear.py, tests/general/QuotesBearTest.py
Add a param to force the preffered quotation.
Closes https://github.com/coala/coala-bears/issues/1005
them. …
=> QuotesBear: Add force_preferred_quotation option

bears/general/FilenameBear.py, tests/general/FilenameBearTest.py
Adds the check if filename has length more than 4096 on UNIX
systems or more than 260 on Windows.
In that case, user will get message about it. 
Closes https://github.com/coala/coala-bears/issues/2003
them.
After you submit your …
=> FilenameBear.py: Add filename length check

bears/general/SpaceConsistencyBear.py
Change docstring indentation according to new standards.
them.
instead. …
=> SpaceConsistencyBear: docstring indentation

bears/general/QuotesBear.py
This changes CAN_DETECT = {'Formatting'} to CAN_FIX = {'Formatting'} as the bear checks and corrects the quotation style.
Closes https://github.com/coala/coala-bears/issues/1571
them. …
=> QuotesBear.py: Change CAN_DETECT to CAN_FIX

bears/js/JSHintBear.py, package.json
This updates the npm jshint requirement to
its most recent version and accommodates
new changes.
them. …
=> JSHintBear.py: Update jshint to 2.9.5

README.rst
Add a comma before run to make sentence more clear.
Fixes https://github.com/coala/coala-bears/issues/2208
them. …
=> README.rst: Add comma to make sentence clear

Gemfile, bears/scss/SCSSLintBear.py, tests/scss/SCSSLintBearTest.py
Updates version of scss_lint and also modifies tests
according to newer versions of scss_lint.
Now it passes all the tests.
Closes https://github.com/coala/coala-bears/issues/2179
them. …
=> SCSSLintBear.py: Update version of scss_lint

PULL_REQUEST_TEMPLATE.md
This changes cobot --> corobo
Closes https://github.com/coala/coala-bears/issues/2145
them. …
=> PULL_REQUEST_TEMPLATE.md: Change cobot to corobo

bears/c_languages/CPPLintBear.py
=> Correct the indentation (#2243)

bear-requirements.txt, bears/python/PyLintBear.py
This upgrade `pylint` to `1.7.2`
and fixes the PylintBear breaks on Python `3.5.0`
Closes https://github.com/coala/coala-bears/issues/1973
them.
When …
=> PyLintBear: PyLintBear breaks on Python `3.5.0`

bears/configfiles/DockerfileLintBear.py, tests/configfiles/DockerfileLintBearTest.py, tests/configfiles/dockerfile_lint_test_files/default_rule.yaml, tests/configfiles/dockerfile_lint_test_files/sample_rule.yaml
Added support for providing a yaml rule file
as an argument.
Closes https://github.com/coala/coala-bears/issues/359
them. …
=> DockefileLintBear: Implement use of rule files

bears/js/PrettierLintBear.py, package.json, tests/js/PrettierLintBearTest.py
This bear uses `prettier` to
format `.js` files.
Closes https://github.com/coala/coala-bears/issues/2130
them. …
=> bears/js: Add PrettierLintBear

bears/natural_language/LanguageToolBear.py
This makes LanguageToolBear throw an warning and use
'en-US' if invalid language is guessed by ``language_check``.
Fixes https://github.com/coala/coala-bears/issues/1848
them. …
=> LanguageToolBear: Use en-US on invalid lang guess

tests/general/DuplicateFileBearTest.py
Closes https://github.com/coala/coala-bears/issues/2050
them.
instead. …
=> DuplicateFileBearTest.py: Use assertEqual as assertEquals has been deprecated.

tests/c_languages/CPPLintBearTest.py
Change 'legal' --> 'legal/copyright' to
make tests more precise.
Closes https://github.com/coala/coala-bears/issues/2266
them. …
=> CPPLintBear: Make tests more precise

bears/configfiles/DockerfileLintBear.py
Closes https://github.com/coala/coala-bears/issues/2259
them.
instead. …
=> DockerfileLintBear.py: Improve docstring

.ci/deps.sh
Display the version tree of the globally
installed npm modules.
Fixes https://github.com/coala/coala-bears/issues/2319
them. …
=> .ci/deps.sh: Display version of npm deps

bears/natural_language/LanguageToolBear.py
This changes `'''` --> `"""`.
Closes https://github.com/coala/coala-bears/issues/1627
them. …
=> LanguageToolBear: Use triple double quotes

bears/python/PEP8Bear.py
URL for asciinema has been added
Closes https://github.com/coala/coala-bears/issues/873
=> PEP8Bear.py: Add asciinema 

.ci/generate_bear_requirements.py
Closes https://github.com/coala/coala-bears/issues/1948
them.
instead. …
=> LogPrinter: Replace LogPrinter with logging

bears/python/PycodestyleBear.py, tests/python/PycodestyleBearTest.py
Allow infinite line length when max_line_length
is set to 0.
Closes https://github.com/coala/coala-bears/issues/2265
them. …
=> PycodeStyleBear:Allow infinite line length

tests/go/GoVetBearTest.py, tests/go/test_files/vet_bad.go, tests/go/test_files/vet_bad_semantics.go, tests/go/test_files/vet_bad_syntax.go
The previous test files had invalid syntax and thus
resulting into failure
Fixes #2337
them. …
=> GoVetBearTest.py: Change go test files

bears/configfiles/DockerfileLintBear.py
This adds the official source link to the SEE_MORE attribute
Closes coala#2287
them. …
=> DockerfileLintBear.py: Add SEE_MORE attribute

.ci/deps.pip.sh, test-requirements.txt
Closes https://github.com/coala/coala-bears/issues/2359
- [x ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [ x] I ran coala over my code locally. (*All commits have to pass
After you submit your …
=> CI Deps: Pip version pin to 9.0.1

tests/js/PrettierLintBearTest.py
Closes: https://github.com/coala/coala-bears/issues/2290
=> PrettierLintBear.py: Add more tests

.coafile
As Default section is deprecated, it is replaced with all in .coafile.
Closes #2397
=> .coafile: Replace Default section with all

.travis.yml
The jobs for unsupported platforms 2.7 & 3.3 do not need to run
so frequently, and any breakages are usually related to upstream
dropping support for 2.7 or 3.3, rather than a local problem.
The master builds will break, and usually we'll need to pin
something to get around the problem.  Ultimately, failure to
verify that these old versions fail in a predictable manner
should not prevent us adding new features or dependencies.
Continues 480c41842
Related to https://github.com/coala/coala/issues/4323
for you to learn this. Just drop us a message and we'll take care of …
=> .travis.yml: Skip unsupported on pull requests

bears/general/QuotesBear.py
Closes https://github.com/coala/coala-bears/issues/2327
=> QuotesBear.py: Add preferred quote in Result

bears/python/PEP8Bear.py, tests/python/PEP8BearTest.py
Allows infinite line length when
max_line_length is set to 0.
Closes https://github.com/coala/coala-bears/issues/2436
them. …
=> PEP8Bear: Add infinite line length

bears/general/LineCountBear.py, tests/general/LineCountBearTest.py
Adds the lower limit for length of file, which is set to 0 by default.
Closes https://github.com/coala/coala-bears/issues/1477
them. …
=> LineCountBear.py: Add min_lines_per_file

bears/js/PrettierLintBear.py
Since this bear's process_output() method uses
process_output_corrected(), it needs CAN_FIX metadata.
Closes https://github.com/coala/coala-bears/issues/2421
them.
After you submit your pull request, **DO NOT click the 'Update …
=> PrettierLintBear.py: Add CAN_FIX metadata

tests/general/KeywordBearTest.py
Tests to check keywordBear offers patches for every commented line
in which keyword is found.
Closes https://github.com/coala/coala-bears/issues/1306
them. …
=> KeywordBearTest.py: Add test for multiple patches

.travis.yml
This reverts commit e44890958290deb79a90d1440543825a962aa3f9.
Travis has upgraded their default Python to 3.6.3.
Related to https://github.com/coala/coala-bears/issues/1864
them.
After you submit your pull request, **DO NOT click …
=> Revert ".travis.yml: Use Python 3.6.1"

Gemfile, bear-requirements.yaml, bears/ruby/RubySecurityBear.py, tests/ruby/RubySecurityBearTest.py, tests/ruby/brakeman_test_files/app/models/account.rb, tests/ruby/brakeman_test_files/app/models/user.rb
Static analysis tool which checks Ruby applications for security vulnerabilities.
Closes: https://github.com/coala/coala-bears/issues/1410
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark …
=> RubySecurityBear.py: Add brakeman

.ci/deps.opam.sh
This makes infer use yojson v1.3.3 and biniou v1.0.6
Closes https://github.com/coala/coala-bears/issues/2006
them. …
=> .ci/deps.opam.sh: Fix uncached opam dependencies

bear-requirements.yaml, bears/configfiles/DockerfileLintBear.py, package.json, tests/configfiles/DockerfileLintBearTest.py, tests/configfiles/dockerfile_lint_test_files/sample_rule.yaml
Modify bear as per dockerfile_lint v0.3.0
Closes https://github.com/coala/coala-bears/issues/2313
them. …
=> DockerfileLintBear: Update bear

bear-requirements.txt, bear-requirements.yaml, bears/vcs/git/GitCommitBear.py
This uses an external library for
fetching and parsing of remotes.
Closes https://github.com/coala/coala-bears/issues/2330
them. …
=> GitCommitBear: parse remote with giturlparse

bears/r/RLintBear.py
=> RLintBear.py: Add asciinema link

setup.py
Related to https://gitlab.com/coala/mobans/merge_requests/3
them.
instead. …
=> setup.py: Sync moban

bear-requirements.yaml, bears/scss/SASSLintBear.py, package.json, tests/scss/SASSLintBearTest.py, tests/scss/test_files/sass-lint.yml
Added a sass-lint Bear for linting SASS/SCSS files
Closes https://github.com/coala/coala-bears/issues/982
- [X ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [X ] I ran coala over my code locally. (*All commits have to pass …
=> Linter: SASSLintBear

bears/vcs/CommitBear.py, tests/vcs/git/GitCommitBearTest.py
Closes https://github.com/coala/coala-bears/issues/2469
them.
instead. …
=> CommitBear: Fix regex for issue id

.gitignore
This adds ignore rule for package-lock.json
Fixes https://github.com/coala/coala-bears/issues/2383
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure …
=> .gitignore: Add ignore rule for package-lock.json

bears/general/InvalidLinkBear.py
Changes the message that is displayed when an HTTP error is generated.
Fixes https://github.com/coala/coala-bears/issues/2435
them. …
=> InvalidLinkBear.py: Correct broken link message

.ci/check_moban.sh, .moban.dt/Gemfile.jj2, .moban.yaml, .travis.yml, Gemfile
Remove cloning of upstream setupmobans.
Use stages, and allow moban to fail.
Related to https://gitlab.com/coala/mobans/merge_requests/25
them.
When …
=> .travis.yml: Add separate moban job

bears/java/CheckstyleBear.py
The jar files on sourceforce have been removed in
favour of GitHub and Maven release files.
Closes https://github.com/coala/coala-bears/issues/2529
them. …
=> CheckstyleBear: Update download location

test-requirements.txt
Made changes to bar the pip versions 9.0.2 and 10.0
specifically from in the test-requirements.txt.
Fixes https://github.com/coala/coala-bears/issues/2404
them. …
=> test-requirements.txt: Change the requirement for pip

.moban.yaml, .travis.yml, setup.py, test-requirements.txt
=> mobanise test requirements

setup.py, test-requirements.txt
=> setup.py: Sync moban template

.ci/deps.go.sh, .moban.yaml, .travis.yml, circle.yml, setup.py, test-requirements.txt
gometalinter maintains its own forks
Closes https://github.com/coala/coala-bears/issues/2534
=> CI: Use gometalinter installer

bears/general/LicenseHeaderBear.py, tests/general/LicenseHeaderBearTest.py, tests/general/licenseheader_test_files/CopyrightWithoutAuthor.java, tests/general/licenseheader_test_files/copyright_with_different_author.txt, tests/general/licenseheader_test_files/copyright_with_given_author.txt, tests/general/licenseheader_test_files/no_copyright.py
This adds a Copyright notice check bear.
Closes https://github.com/coala/coala-bears/issues/2442
them. …
=> bears/general: Add LicenseHeaderBear

.ci/deps.apt.sh, .ci/deps.opam.sh, .ci/deps.pip.sh, .ci/deps.sh, .travis.yml, circle.yml
TERM is set in deps files and works for travis ci
However, for it to work in circleci, it needs to be exported.
closes https://github.com/coala/coala-bears/issues/2514
them. …
=> .ci/: export TERM in deps files

setup.cfg, test-requirements.txt
See https://travis-ci.org/jayvdb/coala-bears/jobs/394478417#L7895
=> CI: Enable pytest-profiling

.ci/deps.apt.sh, .travis.yml
Closes https://github.com/coala/coala-bears/issues/2539
them.
instead. …
=> .travis.yml: Pre-install apt packages

.ci/deps.apt.sh, .travis.yml, test-requirements.txt
Related to https://github.com/coala/coala/issues/5543
them.
instead. …
=> test-requirements.txt: Use pytest 3.6

.ci/generate_bear_requirements.py, Gemfile, bear-requirements.yaml, bears/apertium/ApertiumLintBear.py, bears/python/RadonBear.py, bears/ruby/RubySmellBear.py
=> RubySmellBear: Pin reek version to 4.6-4.x

.ci/generate_bear_requirements.py, Gemfile, bear-requirements.txt, bear-requirements.yaml, bears/apertium/ApertiumLintBear.py, bears/python/RadonBear.py, bears/ruby/RubySmellBear.py, bears/vimscript/VintBear.py
Closes https://github.com/coala/coala-bears/issues/2556
=> VintBear: Prevent use of vim-vint 0.3.19

bears/generate_package.py, tests/generate_packageTest.py
This replaces the user-defined touch
function with library function Path.
Closes https://github.com/coala/coala-bears/issues/2575
them.
When asked for …
=> generate_package.py: Replace touch

.ci/appveyor.yml, .moban.yaml
Closes https://github.com/coala/coala-bears/issues/2567
them.
instead. …
=> appveyor.yml: Sync moban

.ci/deps.apt.sh, .ci/deps.sh, .travis.yml
Closes https://github.com/coala/coala-bears/issues/2302
Related to https://github.com/coala/coala-bears/issues/2592
=> CI: Use cs50/ppa for astyle 3.0.1

.moban.dt/requirements.txt.jj2, .travis.yml, bears/c_languages/CPPLintBear.py, bears/general/AnnotationBear.py, bears/general/IndentationBear.py, bears/haml/HAMLLintBear.py, bears/java/CheckstyleBear.py, bears/natural_language/WriteGoodLintBear.py, bears/python/PyLintBear.py, bears/stylus/StylintBear.py, requirements.txt, tests/general/IndentationBearTest.py, tests/stylus/StylintBearTest.py
Fix several bears which violate 1-based line/column convention
Fixes https://github.com/coala/coala-bears/issues/2563, https://github.com/coala/coala-bears/issues/2574, https://github.com/coala/coala-bears/issues/2573, https://github.com/coala/coala-bears/issues/2572, https://github.com/coala/coala-bears/issues/2562, https://github.com/coala/coala-bears/issues/2393
them.
our bot will still report the …
=> Fix several bears which violate 1-based line/column convention

.moban.dt/requirements.txt.jj2, .travis.yml, bears/general/AnnotationBear.py, bears/general/IndentationBear.py, requirements.txt, tests/general/IndentationBearTest.py
Fixes https://github.com/coala/coala-bears/issues/2589
=> AnnotationBear: Use comment_delimiters

.ci/deps.apt.sh, .ci/deps.sh, .moban.dt/requirements.txt.jj2, .travis.yml, bears/c_languages/CPPLintBear.py, bears/general/AnnotationBear.py, bears/general/IndentationBear.py, bears/haml/HAMLLintBear.py, bears/java/CheckstyleBear.py, bears/natural_language/WriteGoodLintBear.py, bears/python/PyLintBear.py, bears/stylus/StylintBear.py, circle.yml, requirements.txt, tests/general/IndentationBearTest.py, tests/stylus/StylintBearTest.py
Closes https://github.com/coala/coala-bears/issues/2592
Unfortunately also adds more use of Travis CI's addon, which is a bit dodgy atm
https://github.com/coala/coala-bears/issues/2591
=> .travis.yml: Remove sudo

.ci/generate_bear_requirements.py, Gemfile, bear-requirements.yaml, bears/csv/CSVLintBear.py, bears/sql/SQLintBear.py
~~~Blocked by https://github.com/coala/coala-bears/pull/2559 and other breakages~~~
=> Add gem versions

bears/js/ESLintBear.py, tests/js/ESLintBearTest.py
Fixes https://github.com/coala/coala-bears/issues/2533
=>  ESLintBear: Fix KeyErrors for file level errors

.ci/deps.sh
Continues https://github.com/coala/coala-bears/pull/2536
=> .ci/deps.sh: Remove go deps now in .ci/deps.go.sh

bear-requirements.txt, bear-requirements.yaml, bears/python/requirements/PySafetyBear.py, tests/python/requirements/PySafetyBearTest.py, tests/python/requirements/PySafetyBearWithoutMockTest.py
Update PySafetyBear so that it support the
latest safety version 1.8.2
Related to https://github.com/coala/coala-bears/issues/2511
Related to https://github.com/coala/coala-bears/issues/1684
=> PySafetyBear: Update PySafetyBear

bears/general/CPDBear.py
Update URL from https://pmd.github.io/pmd-5.4.1/usage/cpd-usage.html
to https://pmd.github.io/pmd-6.4.0/pmd_userdocs_cpd.html
Closes https://github.com/coala/coala-bears/issues/2518
them.
After you submit your pull request, **DO …
=> CPDBear: Update URL

bears/Constants.py
The VERSION variable is added to __all__ in bears/Constants.py
Closes https://github.com/coala/coala-bears/issues/2623
them. …
=> bears/Constants.py : Adds VERSION to all

bears/vcs/VCSCommitMetadataBear.py, bears/vcs/git/GitCommitMetadataBear.py, tests/vcs/VCSCommitMetadataBearTest.py, tests/vcs/git/GitCommitMetadataBearTest.py
This adds a new meta bear that returns HiddenResult
of commit analysis for other bears to use.
them. …
=> VCSCommitMetadataBear: New meta bear for analyzing commits

.ci/check_unsupported.sh, bear-requirements.txt, bear-requirements.yaml, bears/python/MypyBear.py
This upgrades mypy to the latest release.
Closes https://github.com/coala/coala-bears/issues/2601
them. …
=> MypyBear: Upgrade mypy

bears/general/LineLengthBear.py, tests/general/LineLengthBearTest.py
This migrates `LineLengthBear` to its respective
aspects and tastes.
Closes https://github.com/coala/coala-bears/issues/2602
them. …
=> LineLengthBear: Migrate to aspects

setup.cfg, tests/documentation/DocGrammarBearTest.py, tests/documentation/DocumentationStyleBearTest.py, tests/python/BanditBearTest.py
setup.cfg currently contains:
python_functions = *_test
This has the effect of allowing functions like `test(..)` to
exist and not be considered test functions.  Two sets have appeared.
When pytest defaults are used, these two sets of functions called
`test(..)` result in pytest loading failures as they are not valid
pytest test functions, but are helper functions for unittests.
The arguments on these functions should be fixture names, and they
are not.  This confuses people who know pytest naming conventions.
for you to learn this. Just drop us a message and we'll take care …
=> setup.cfg: Remove pytest config 'python_functions'

bears/python/PycodestyleBear.py, tests/python/PycodestyleBearTest.py
This migrates `PycodestyleBear` to its respective
aspects and tastes.
Closes https://github.com/coala/coala-bears/issues/2656
them. …
=> PycodestyleBear: Migrate bear to aspects

.coafile
The attribute max_line_length changed to 80.
Closes https://github.com/coala/coala-bears/issues/2662
them. …
=> .coafile: Set max line characters to 80

.ci/appveyor.yml, setup.py, test-requirements.txt
=> Sync templates

bear-requirements.yaml, bears/gherkin/GherkinLintBear.py, package.json, tests/gherkin/GherkinLintBearTest.py, tests/gherkin/config_files/.gherkin-lintrc, tests/gherkin/test_files/.gherkin-lintrc, tests/gherkin/test_files/DuplicateFeatureName-Pt1.feature, tests/gherkin/test_files/DuplicateFeatureName-Pt2.feature, tests/gherkin/test_files1/DuplicateFeatureName-Pt1.feature, tests/gherkin/test_files1/DuplicateFeatureName-Pt2.feature, tests/gherkin/test_files1/DuplicateScenarioName.feature, tests/gherkin/test_files1/DuplicateTags.feature, tests/gherkin/test_files1/MultipleEmptyLines.feature, tests/gherkin/test_files1/NoHomogenousTags.feature, tests/gherkin/test_files1/NoNewLineAtEOF.feature, tests/gherkin/test_files1/NoRestrictedTags.feature, tests/gherkin/test_files1/NoScenarios.feature, tests/gherkin/test_files1/NoSuperfluousTags.feature, tests/gherkin/test_files1/OnlyScenarioOutlines.feature, tests/gherkin/test_files1/PartiallyCommentedTagLine.feature, tests/gherkin/test_files1/ScenarioOutlineWithoutExamples.feature, tests/gherkin/test_files1/TrailingSpaces.feature, tests/gherkin/test_files1/TrailingTab.feature, tests/gherkin/test_files1/UnnamedFeature.feature, tests/gherkin/test_files1/UnnamedScenario.feature, tests/gherkin/test_files1/UseAnd.feature, tests/gherkin/test_files2/MultipleBackgrounds.feature, tests/gherkin/test_files2/MultipleFeatures.feature, tests/gherkin/test_files2/TagOnBackground.feature
Add bear using gherkin-lint
Closes https://github.com/coala/coala-bears/issues/2214
=> GherkinLintBear.py: Add new lint bear

bear-requirements.yaml, bears/js/ESLintBear.py, package.json, tests/js/ESLintBearTest.py
Add document rules from eslint
Closes https://github.com/coala/coala-bears/issues/1951
them. …
=> ESLintBear.py: Add settings from eslint

bears/vcs/git/GitRevertInspectBear.py, tests/vcs/git/GitRevertInspectBearTest.py
Bear to inspect git revert commits
them.
instead.
Please consider helping …
=> GitRevertInspectBear.py: New bear

bears/c_languages/GNUIndentBear.py
Add infinite length when
max_line_length is set to 0
Fixes coala/coala-bears#2669
them. …
=> GNUIndentBear.py: Fix max_line_length=0

tests/python/BanditBearTest.py
Allows the B701 message to vary slightly for bandit 1.5
Closes https://github.com/coala/coala-bears/issues/2678
them. …
=> BanditBearTest.py: Support bandit 1.5

tests/julia/JuliaLintBearTest.py
=> JuliaLintBearTest: Remove timeout

bears/apertium/ApertiumLintBear.py
This removes the incorrect line break and unnecessary word 'section'.
Closes https://github.com/coala/coala-bears/issues/1965
them. …
=> ApertiumLintBear.py: Remove line break

.ci/check_unsupported.sh, setup.py, test-requirements.txt
=> Sync with new moban

bears/python/PEP8NotebookBear.py
In the PEP8NotebookBear.py file there was a spelling mistake at Line 11.
The change was needed for clearer understanding.
Closes https://github.com/coala/coala-bears/issues/2703
them. …
=> PEP8NotebookBear.py: Spell mistake fix

bear-requirements.txt, bear-requirements.yaml, bears/yaml/YAMLLintBear.py
Closes https://github.com/coala/coala-bears/issues/2712
them.
instead. …
=> YAMLLintBear: Update version to 1.12.0

.ci/generate_bear_requirements.py, .moban.dt/DESCRIPTION.jj2, .moban.yaml, bear-requirements.yaml, bears/r/FormatRBear.py, bears/r/RLintBear.py
This adds generating requirements for R bears in generate_bear_requirements.py
Closes https://github.com/coala/coala-bears/issues/2482
=> add generating requirements for R bots

bears/python/PythonPackageInitBear.py
Record an asciinema that shows the usage of PythonPackageInitBear.py
Closes https://github.com/coala/coala-bears/issues/1167
them. …
=> PythonPackageInitBear.py: Create Asciinema

bears/python/BanditBear.py
Closes https://github.com/coala/coala-bears/issues/2740
- [yes ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [yes ] I ran coala over my code locally. (*All commits have to pass
After you submit …
=> Add asciinema video to BanditBear

.ci/generate_bear_requirements.py, bear-languages.yaml, bear-requirements.yaml
This generates a yaml file mapping the languages used by every bear.
Closes https://github.com/coala/coala-bears/issues/2479
them. …
=> generate_bear_requirements.py: Add language file

bears/ruby/RubyFastererBear.py
RubyFastererBear.py >> Add asciinema URL
- [yes ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [N/A ] I ran coala over my code locally. (*All commits have to pass …
=> Add asciinema video to RubyFastererBear

bear-languages.yaml, bears/general/LineContinuationBear.py, tests/general/LineContinuationBearTest.py
Closes https://github.com/coala/coala-bears/issues/2427
them.
instead. …
=> LineContinuationBear.py: Add line continuation bear

.moban.dt/bears-setup.cfg.jj2, .moban.yaml, .nocover.yaml, .travis.yml, bear-requirements.txt, bear-requirements.yaml, bears/general/MementoBear.py, setup.cfg, setup.py, test-requirements.txt, tests/conftest.py
=> setup.cfg: Use template

bear-languages.yaml, bear-requirements.txt, bear-requirements.yaml, bears/sql/SQLFormatBear.py, tests/sql/SQLFormatBearTest.py
Closes https://github.com/coala/coala-bears/issues/2406
them.
instead. …
=> SQLFormatBear.py: Add sqlparse bear

bears/matlab/MatlabIndentationBear.py
This pull request adds asciinema for MatLab Bear
Closes https://github.com/coala/coala-bears/issues/1221
=> Adds asciinema to MatLab Bear

bears/documentation/DocGrammarBear.py, tests/documentation/DocGrammarBearTest.py
Add test to check installation of language_check
Closes https://github.com/coala/coala-bears/issues/2767
them. …
=> DocGrammarBear: Remove use of generic no cover

bears/general/CPDBear.py, tests/general/CPDBearTest.py
Add test to check for prerequisites
Closes https://github.com/coala/coala-bears/issues/2766
them. …
=> CPDBear: Remove use of generic no cover

bears/python/requirements/PySafetyBear.py, tests/python/requirements/PySafetyBearTest.py
Closes https://github.com/coala/coala-bears/issues/2773
them.
instead. …
=> PySafetyBear: Remove use of generic no cover

bears/python/PyImportSortBear.py
This pull request adds asciinema to PyImportSortBear.
Closes https://github.com/coala/coala-bears/issues/876
=> PyImportSortBear.py: Adds asciinema

bears/natural_language/LanguageToolBear.py, tests/natural_language/LanguageToolBearTest.py
Add test to check language-tool is installed.
Closes https://github.com/coala/coala-bears/issues/2772
them. …
=> LanguageToolBear: Remove use of generic no cover

bears/vhdl/VHDLLintBear.py, tests/vhdl/VHDLLintBearTest.py
Add test to check for prerequisites
Closes https://github.com/coala/coala-bears/issues/2775
them. …
=> VHDLLintBear: Remove use of generic no cover

bears/java/JavaPMDBear.py, tests/java/JavaPMDBearTest.py
Add test to check for prerequisites
Closes https://github.com/coala/coala-bears/issues/2769
them. …
=> JavaPMDBear: Remove use of generic no cover

.ci/appveyor.yml
Ruby 2.2 is very old, and the AppVeyor version is 2.2.6
while the latest 2.2 is 2.2.10
Related to https://github.com/coala/coala-bears/issues/1305
them. …
=> .ci/appveyor.yml: Use Ruby 2.4

.ci/appveyor.yml, bears/css/CSSLintBear.py, bears/css/StyleLintBear.py, bears/hypertext/BootLintBear.py, bears/hypertext/HTMLHintBear.py, bears/js/HappinessLintBear.py, bears/js/JSComplexityBear.py, bears/js/JSStandardBear.py, bears/js/PrettierLintBear.py, bears/natural_language/WriteGoodLintBear.py, bears/pug/PugLintBear.py, bears/stylus/StylintBear.py, bears/yaml/RAMLLintBear.py
=> Appveyor node bears

.ci/deps.go.sh, .travis.yml, tests/markdown/MarkdownBearTest.py
=> 20181216 fixes

bears/vcs/mercurial/HgCommitBear.py
=> HgCommitBear.py: Add asciinema.

README.rst
Fixes issue https://github.com/coala/coala-bears/issues/2838
=> README.rst: Fix typo in words `newcomers' guide`

.travis.yml
Removed old golang repository links from .travis.yml
Setup gimme to install the latest stable version of golang
v1.11.5 available at the time of the change
Closes https://github.com/coala/coala-bears/issues/2843
them.
After you …
=> .travis.yml: Update Golang version to 1.11.5

bears/python/requirements/PySafetyBear.py
Adds asciinema for PySafetyBear.
Previously, no asciinema was present in PySafetyBear.py file.
Adds asciinema for PySafetyBear.
Fixes #2371 
them. …
=> PySafetyBear.py: Adds Asciinema for PySafetyBear.

.travis.yml
The script isnt ready for coala-bears, and may not be suitable.
them. …
=> .travis.yml: Remove use of check_setuptools.py

tests/general/LineContinuationBearTest.py
Escape backslash correctly, to act as line continuation operator
Lines 41 and 42 are finally hit and hence
increases LineContinuationBear.py coverage from 92% to 100%
Fixes https://github.com/coala/coala-bears/issues/2866
them. …
=> LineContinuationBearTest.py: Escape backslash

setup.cfg, test-requirements.txt
Sync all the good changes from coala/mobans repository
Mobans job will still continue failing until coala/mobans is synced back
Closes https://github.com/coala/coala-bears/issues/2853
them.
After you submit your pull request, **DO …
=> moban: Sync from moban templates

bears/vcs/git/GitRevertInspectBear.py
Closes: https://github.com/coala/coala-bears/issues/2738
them.
instead. …
=> GitRevertInspectBear: Add asciinema

tests/natural_language/LanguageToolBearTest.py
Fixes https://github.com/coala/coala-bears/issues/2796
them.
instead. …
=> LanguageToolBearTest.py: Remove SkipTest warning

bears/vcs/git/GitIgnoreBear.py, tests/vcs/git/GitIgnoreBearTest.py
Closes https://github.com/coala/coala-bears/issues/2610
them.
=> vcs/git: Add GitIgnoreBear

setup.py
=> Sync templates with moban

bears/csv/CSVLintBear.py
Provide some more details on what basis
the csv file is being validated.
them. …
=> CSVLintBear.py: Improve Documentation

.ci/check_setuptools.py
Closes https://github.com/coala/coala-bears/issues/2956
=> moban: Sync templates
