coala/coala-bears

- bears/general/InvalidLinkBear.py
- bears/tests/general/InvalidLinkBearTest.py
- requirements.txt
Check for broken links
Search for every link in a file, and send a GET
request to each of them to check if they are valid.
If any of them do not send a HTTP status 200 back, then:
- if the status code is 30x:
the redirect url is fetched and a diff is shown to update the
url.
- if the status code is 50x or 40x:
The message "Broken link - unable to connect to this url."
along with the status code is displayed.
- if the GET request fails:
The message "Broken link - unable to connect to this url."
is displayed.
InvalidLinkBear also checks for internet connection, as a
prerequisite.
Fixes https://github.com/coala-analyzer/coala-bears/issues/29
> bears/general: Add InvalidLinkBear

- .gitignore
Removed: coala.1, org.coala_analyzer.v1.service
as they were redundant
Modified coala.egg_info to be, more generally, *.egg-info.
Fixes https://github.com/coala-analyzer/coala-bears/issues/65
> .gitignore: Update to reflect coala repo

- bears/general/InvalidLinkBear.py
A timeout of 1s is added so that the tests do not get timed out.
Fixes https://github.com/coala-analyzer/coala-bears/issues/111
> InvalidLinkBear: Set timeout for requests

- bears/__init__.py
Add the version constants from Constants.py. Add variable "__version__".
Fixes https://github.com/coala-analyzer/coala-bears/issues/84
> bears/__init__.py: import constants

- bears/python/PyDocStyleBear.py
- requirements.txt
- tests/python/PyDocStyleBearTest.py
Uses pydocstyle(https://github.com/PyCQA/pydocstyle) to check for
docstring style.
Fixes https://github.com/coala-analyzer/coala-bears/issues/130
> bears: Add PyDocStyleBear

- setup.cfg
`test-requirements.txt` has been added to addopts --ignore flag which ensures
it doesn't get picked up when using `py.test`
Fixes https://github.com/coala-analyzer/coala-bears/issues/71
Sorry for opening a new PR, the old one had a dirty commit history and I no longer had that copy of the repo. Closing the previous one.
> setup.cfg: Ignore file test-requirements.txt

- requirements.txt
Previous coala versions didn't have coalang files
packaged into them, and also had some problems with the keys
version 0.4.2.dev20160304094246 has all that fixed and that is also
required by the upcoming IndentationBear
> requirements: Update coala version

- .ci/deps.sh
Downloads and installs dart-sdk only if it doesn't exist already.
Fixes https://github.com/coala-analyzer/coala-bears/issues/157
> deps.sh: Don't download dart-sdk if it exists

- requirements.txt
Apparently radon did something that breaks our builds, this needs to be
investigated further. This is a hotfix and not intended to last.
Related: https://github.com/rubik/radon/issues/82
Related: https://github.com/coala-analyzer/coala/issues/1852
> requirements.txt: Fix radon version

- bears/ruby/RubySyntaxBear.py
- tests/ruby/RubySyntaxBearTest.py
RubyLintBear is now RubySyntaxBear because of
a new `ruby-lint` bear to be added and this name
makes more sense.
Fixes: coala-analyzer#190
> Ruby syntax bear

- bears/c_languages/codeclone_detection/ClangCountVectorCreator.py
- bears/c_languages/codeclone_detection/CloneDetectionRoutines.py
- bears/c_languages/codeclone_detection/CountVector.py
- tests/c_languages/codeclone_detection/ClangCountVectorCreatorTest.py
- tests/c_languages/codeclone_detection/ClangCountingConditionsTest.py
- tests/c_languages/codeclone_detection/CountVectorTest.py
Instead of name mangling added one more property to the CountVector
class to save the type of variable in the original code.
Fixes https://github.com/coala-analyzer/coala-bears/issues/38
> Clone Detection: Made variable type a property

- .ci/deps.sh
Earlier we had removed the `-qq` flag in apt-get and
not added the -y. -qq automatically added the -y and so
If a rebuild without cache is done, this will hang.
> deps: Auto reply yes for prompts in apt-get

- setup.py
Shifted assertion for python3 above all imports, as some of
the imports might not work with python2.
Fixes https://github.com/coala-analyzer/coala-bears/issues/223
> setup: Change position of all imports

- Gemfile
- bears/ruby/RuboCopBear.py
- tests/ruby/RuboCopBearTest.py
Add `rubocop` support for Ruby static code analyzer.
Fixes: https://github.com/coala-analyzer/coala-bears/issues/189
> bears/ruby: Add RuboCopBear

- bears/java/InferBear.py
Fixes infer's computing dependencies which were shown as warnings.
> InferBear.py: Fix wrong warnings

- bears/r/RLintBear.py
For a prerequisite command to run, now we can use
prerequisite_command for the command to run and
prerequisite_fail_msg for the error message.
> RlintBear: refactor prerequisite checking

- bears/r/FormatRBear.py
`prerequisite_command` and `prerequisite_message` added
to FormatRBear to check prerequisite.
Fixes https://github.com/coala-analyzer/coala-bears/issues/221
> bears/r: Add Skip condition for FormatRBear

- bears/js/JSHintBear.py
- tests/js/JSHintBearTest.py
Add autogeneration of config file for JSHint from settings using the
config_file function from Lint
Fix https://github.com/coala-analyzer/coala-bears/issues/115
> JSHintBear.py: Add autogeneration of config file

- bears/general/InvalidLinkBear.py
The request time out period in InvalidLinkBear file should be 5 sec
at least to verify the link.
Fixes https://github.com/coala-analyzer/coala-bears/issues/240
> InvalidLinkBear: Update request time out period

- bears/perl/PerlCriticBear.py
- tests/perl/PerlCriticBearTest.py
- tests/perl/testfiles/.perlcriticrc
PerlCriticBear currently gives an exception when ran because the
`--config` argument does not exist. This should be `--profile`
instead.
Also, due to a known bug in temporary file creation, the inline
configuration file in PerCriticBearTest is moved to a directory
testfiles/ and the configuration file is placed there.
Fixes https://github.com/coala-analyzer/coala-bears/issues/109
> PerlCriticBear: Replace inline config with file

- requirements.txt
Radon has fixed it's requirements.txt and this should help users with
dependency problems.
> requirements: Bump radon

- bears/xml/XMLBear.py
- tests/xml/test_files/xsd-error.xml
Errors were shown as logs instead of errors. Corrected the processing of
output to show the error messages.
Fixes https://github.com/coala-analyzer/coala-bears/issues/251
> XMLBear: Process error correctly

- bears/c_languages/codeclone_detection/ClangCountingConditions.py
- tests/c_languages/codeclone_detection/ClangCountingConditionsTest.py
- tests/c_languages/codeclone_detection/conditions_samples.c
Add support for switch/case statements in ClangCodeCloneDetectionBear
as  it does not currenly support it.This would count the condition with
the Is condition CC and the bodies with the In condition CCs so nested
things are recognized right.
Fixes https://github.com/coala-analyzer/coala-bears/issues/39
> ClangCodeCloneDetectionBear: Add switch support

- bears/vcs/git/GitCommitBear.py
- bears/xml/XMLBear.py
- tests/vcs/git/GitCommitBearTest.py
- tests/xml/test_files/xsd-error.xml
Errors were shown as logs instead of errors. Corrected the processing of
output to show the error messages.
Fixes https://github.com/coala-analyzer/coala-bears/issues/251
> Bugfix backporting to 0.1

- bears/css/CSSAutoPrefixBear.py
- package.json
- tests/css/CSSAutoPrefixBearTest.py
This bear uses PostCSS plugin autoprefixer to add
vendor prefixes to CSS rules.
Fixes https://github.com/coala-analyzer/coala-bears/issues/280
> bears/css: Add AutoPrefixBear

- bears/julia/JuliaLintBear.py
Add prerequisite_command and prerequisite_fail_msg
to JuliaBear.
Fixes https://github.com/coala-analyzer/coala-bears/issues/222
> bears/julia: Add Skip Condition for JuliaBear

- bears/c_languages/codeclone_detection/ClangComplexityBear.py
- requirements.txt
- tests/c_languages/codeclone_detection/ClangComplexityBearTest.py
- tests/c_languages/codeclone_detection/empty_declarations.c
Fixes https://github.com/coala-analyzer/coala-bears/issues/81
But, here is still a problem. If we have:
```c
int f(int a) {
if (a)
return 0;
else
return 1;
if (!a)
return 2;
else
return 3;
}
```
statement `if (!a)` is unreachable, but I will not catch that and will have 2 decision points. In addition, I'll count 5 exit points (extra at the end of the block) instead of 2.
> Add ClangComplexityBear

- .ci/appveyor.yml
Clang x64 bindings were installed, but these cause some tests to hang.
See
https://github.com/appveyor/ci/issues/495
https://github.com/appveyor/ci/issues/688
> CI: Disable clang-related tests on appveyor

- .ci/appveyor.yml
- .ci/deps.nltk.sh
- .ci/deps.osx.sh
- .ci/deps.sh
- bears/vcs/git/GitCommitBear.py
- circle.yml
- requirements.txt
- tests/vcs/git/GitCommitBearTest.py
This commit adds `check_imperative` method in `GitCommitBear`.
The method checks if a shortlog is in imperative mood or not.
If the shortlog isn't in imperative mood then it'd throw an error
message including the invalid words that are the cause for being non
imperative so that user could get some hint and fix his commit.
Fixes https://github.com/coala-analyzer/coala-bears/issues/243
> GitCommitBear: Add imperative check in shortlog

- tests/r/RLintBearTest.py
Previously, lintr didn't account for spaces around all infix
operators.
This commit introduces that:
https://github.com/jimhester/lintr/commit/c7eda9e370f3e5e8856e8695af477214fc428f3b
Now tests are being changed to conform to the new rule.
> RLintBearTest: Conform to lintr's spacing rule

- bears/vcs/git/GitCommitBear.py
- tests/vcs/git/GitCommitBearTest.py
The metadata is now retrieved from `check_shortlog` and `check_body` to
avoid signature duplication overhead.
> GitCommitBear: Divide metadata signature

- README.rst
README contains a table with languages that coala provides
support for. Also modifies the number of languages 2 lines
before the table.
Fixes https://github.com/coala-analyzer/coala-bears/issues/378
> README.rst: Add table with languages supported

- bears/python/PyLintBear.py
Allows to disable single rules via ignore statements inside code.
> PyLintBear: Use origin regex field

- bears/general/AnnotationBear.py
- tests/general/AnnotationBearTest.py
The Bear searches for strings and comments in a file
and yields them as results with the appropriate ranges
Also takes care of:
1. Comments within comments
2. Comments within strings and
3. Strings wihin comments
Fixes https://github.com/coala-analyzer/coala-bears/issues/37
> AnnotationBear: Add AnnotationBear

- bears/c_languages/GNUIndentBear.py
- bears/css/CSSAutoPrefixBear.py
- bears/go/GoImportsBear.py
- bears/go/GoReturnsBear.py
- bears/go/GofmtBear.py
- bears/markdown/MarkdownBear.py
- requirements.txt
Due to API changes, calling it Linter v2.1 API, we need to adapt.
> bears: Adapt to new Linter API

- README.rst
It is no longer used.
Fixes https://github.com/coala-analyzer/coala/issues/2148
> README.rst: Remove OSX section

- bears/vcs/git/GitCommitBear.py
The command python -m nltk.downloader punkt
was modify to take python3
Fixes https://github.com/coala-analyzer/coala-bears/issues/454
> GitCommitBear: Change python -> python3

- .ci/deps.sh
- bears/go/GoErrCheckBear.py
- tests/go/GoErrCheckBearTest.py
Used errcheck to find function calls
that have unchecked errors in Go.
Fixes https://github.com/coala-analyzer/coala-bears/issues/31
> bears/go: Add GoErrCheckBear

- setup.py
Here Environment classifier changes to 'Plugins' from 'Console'.
Environment :: Console -> Environment :: Plugins
Fixes https://github.com/coala-analyzer/coala-bears/issues/449
> setup.py: Change Environment classifier

- bears/c_languages/GNUIndentBear.py
Change how `shlex.split` is imported and used to be more consistent with
other bears.
Fixes https://github.com/coala-analyzer/coala-bears/issues/352
> GNUIndentBear: use `shlex.split` explicitly

- bears/general/AnnotationBear.py
- tests/general/AnnotationBearTest.py
- tests/general/test_files/test.coalang
coala has a new external coalang feature, which is
useful for testing and also gives users an option to use their own
coalang files.
> AnnotationBear: Allow external coalang

- bears/general/IndentationBear.py
- tests/general/IndentationBearTest.py
- tests/general/test_files/test.coalang
It is a generic indent bear, which looks for a start and end
indent eg: { : }  if they are specified.
eg: "{"  where { is an
indent start.
it does not however support hanging indents or absolute indents of
any sort, also indents based on keywords are not supported yet.
for example:
if(something)
does not get indented
changes to:
if(something)
does not get indented
Fixes https://github.com/coala-analyzer/coala-bears/issues/40
> bears/general: Add IndentationBear

- bears/julia/JuliaLintBear.py
A LintResult is now returned, instead of printing it. This has
to be displayed.
https://github.com/tonyhffong/Lint.jl/commit/79c647
> JuliaLintBear: Use display() to print result

- bears/js/HappinessLintBear.py
- package.json
- tests/js/HappinessLintBearTest.py
This bear uses `happiness` to
lint `.js` files.
Closes http://github.com/coala-analyzer/coala-bears/issues/588
> bears/js: Add HappinessLintBear

- .codecov.yml
Fix to ensure builds don't pass
if coverage is not 100%.
> codecov.yml: Fix it

- package.json
Add ``name`` and ``version`` fields
so that ``npm install`` doesn't fails.
Fixes https://github.com/coala-analyzer/coala-bears/issues/642
> package.json: Add name and version

- bears/python/YapfBear.py
``str(blank_line_before_nested_class_or_def)`` is
completely useless here.
> YapfBear: Remove useless element

- bears/go/GoErrCheckBear.py
- bears/java/InferBear.py
- bears/js/JSComplexityBear.py
- bears/swift/TailorBear.py
- bears/typescript/TSLintBear.py
Remove arguments from URLs so
embedding in websites works properly.
Closes https://github.com/coala-analyzer/coala-bears/issues/662
> bears: Fix ASCIINEMA_URLS

- bears/python/VultureBear.py
- requirements.txt
- tests/python/VultureBearTest.py
This bear uses `vulture` to detect
unused code.
Closes https://github.com/coala-analyzer/coala-bears/issues/646
> bears/python: Add VultureBear

- bears/general/CPDBear.py
Fixed the typo.
Closes https://github.com/coala-analyzer/coala-bears/issues/606
> CPDBear: Fix typo omparison to comparison

- bears/general/CPDBear.py
Using brew to install PMD on MacOS will provide a `pmd` binary
instead of the `run.sh` mentioned in the official docs.
This change will allow CPDBear to use whichever variant is available.
> Look for `pmd` binary for CPDBear

- requirements.txt
We were holding off on this version bump because of a bug in 3.2, but
this issue has now been fixed in 3.2.1, and the buggy version was
removed from PyPI.
Closes https://github.com/coala-analyzer/coala-bears/issues/509
> Bump NLTK version to 3.2

- bears/python/YapfBear.py
This was already changed in requirements.txt, but was forgotten in the bear class.
Closes https://github.com/coala-analyzer/coala-bears/issues/742
> YapfBear: Update yapf requirement to 0.11

- bears/python/YapfBear.py
- tests/python/YapfBearTest.py
Syntax verification is supposed to be a private feature in yapf, used for debugging, but they're still defaulting its flag to True on the public FormatFile function. We need to set it to False to disable syntax error checking in yapf (which seems to be an unmaintained feature of it, since it raises exceptions on async/await and py2 print syntax), see discussion at https://github.com/google/yapf/issues/293
Fixes https://github.com/coala-analyzer/coala-bears/issues/738
Also filed an upstream issue here https://github.com/google/yapf/issues/297
> YapfBear: Disable syntax verification

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
A lot of people aren't using this bear because they don't want redirects
to be corrected. We should build a better heuristic until we make that
functionality default and we need that setting anyway.
Closes https://github.com/coala-analyzer/coala-bears/issues/528
> InvalidLinkBear: Add follow_redirects setting

- requirements.txt
Although we don't need t directly, this release breaks coala. This is a
hotfix and should be reverted when our dependencies have adapted.
Appropriate issues are being filed as I write this.
> requirements.txt: Add pyflakes

- .coafile
- bears/general/KeywordBear.py
- tests/general/KeywordBearTest.py
Rename of weirdly named settings: ci_keywords to keywords_case_insensitive
and cs_keywords to keywords_case_sensitive.
Closes https://github.com/coala-analyzer/coala-bears/issues/756
> KeywordBear: Rename arguments

- bears/c_languages/CSecurityBear.py
- tests/c_languages/CSecurityBearTest.py
Remove `neverignore` setting from the bear as this should not be done by the bear.
Fixes https://github.com/coala-analyzer/coala-bears/issues/680
> CSecurityBear: Remove neverignore from settings

- bears/js/ESLintBear.py
In some cases, eslint fails. Because of this, the user can't see any
results, nor does the user see any warning that it failed. We now show
the stderr to the user as a WARNING.
Fixes https://github.com/coala-analyzer/coala-bears/issues/730
> ESLintBear: Show errors shown in stderr

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
The name of the identifier is changed from ignore_regex to
link_ignore_regex , as the issue addresses that the name is too generic.
Fixes https://github.com/coala-analyzer/coala-bears/issues/746
> InvalidLinkBear: Change identifier ignore_regex to link_ignore_regex

- bears/general/CPDBear.py
CPD output did not properly show all duplicate lines of a code
because a file length was read from XML element instead of an actual file.
> CPDBear: Fix incorrect file length reading

- bears/js/JSComplexityBear.py
- bears/js/JSONFormatBear.py
- requirements.txt
- tests/js/JSComplexityBearTest.py
- tests/js/JSONFormatBearTest.py
JSComplexityBear.py and JSONFormatBear.py had a common function
get_available_decodeerror, which can lead to differences in future,
hence, it is unified in the compat module, from where the error is
imported.
Fixes https://github.com/coala-analyzer/coala/issues/2743
> Remove duplicated function and unify it in compat

- bears/vcs/git/GitCommitBear.py
- tests/vcs/git/GitCommitBearTest.py
Sometimes the output messages are unclear, and the
newcomers do not know what they did wrong. This
commit helps making the output messages clearer.
> GitCommitBear: Improve output messages

- bears/haskell/HaskellLintBear.py
Used PyImportSortBear to sort the imports.
Closes https://github.com/coala/coala-bears/issues/355
> HaskellLintBear.py: Sort imports alphabetically

- .ci/appveyor.yml
It was needed back when setup.py was implicitly downloading dependent jars.
Fixes https://github.com/coala-analyzer/coala-bears/issues/800
> appveyor.yml: Removed 'setup.py --help' command

- .coafile
This will catch things like:
- A (wrong) space before a colon
- Missing space after the colon
- Trailing period after shortlog
- Lower case char after the colon
all automatically!
> coafile: Improve commit message checking

- package.json
tslint does not install without typescript >=1.7.3
also being declared as a dependency.
Fixes https://github.com/coala/coala-bears/issues/866
> Add tslint peer dependency typescript >=1.7.3

- tests/LocalBearTestHelper.py
Adds missing doc_string for execute_bear
Closes https://github.com/coala/coala-bears/issues/321
Includes improvements based on feedback from https://github.com/coala/coala-bears/pull/547
> LocalBearTestHelper.py: Adds doc_string for execute_bear

- bears/natural_language/SpellCheckBear.py
Updates URL from https://pypi.python.org/pypi/scspell 
to https://pypi.python.org/pypi/scspell3k.
Fixes https://github.com/coala/coala-bears/issues/908
> SpellCheckBear.py: Update URL for scspell

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
URLs wrapped within backticks are parsed correctly now,
\`https://coala.io/` -> https://coala.io
Added ` in the non-capturing group of regex
Also, added test for the same
Fixes https://github.com/coala/coala-bears/issues/860
> InvalidLinkBear: Parse URLs wrapped with backticks

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
Modify regex to ignore placeholders like
``%s``,``%d``,``%f``, etc. and add corresponding
tests to InvalidLinkBearTest.py
Closes https://github.com/coala/coala-bears/issues/758
> InvalidLinkBear.py: Amend regex

- RELEASE_NOTES.rst
Added a new line to make sure the bulleting starts with the correct item
previously AutoPrefixBear was on the same line as NewBears and was not getting a bullet, 
now it will look more uniform
Removed extra space to align for with backlash
Fixes https://github.com/coala/coala-bears/issues/919
> RELEASE_NOTES.rst: Fixed Spaceing

- bears/coffee_script/CoffeeLintBear.py
- bears/java/JavaPMDBear.py
- bears/js/JSHintBear.py
- bears/js/JSONFormatBear.py
- bears/natural_language/WriteGoodLintBear.py
- bears/ruby/RubySmellBear.py
- requirements.txt
The module coala_utils.param_convertion.py was
renamed to coala_utils.param_conversion.py in
coala_utils 0.4.10. This caused some bears to throw
import errors.
This commit fixes the affected import lines.
Fixes https://github.com/coala/coala-bears/issues/945
> bears: Fix imports

- bears/general/InvalidLinkBear.py
Remove 'ftp' from regex variable in `find_links_in_file()`
method because Python `requests` library can't fetch the FTP
status code.
Closes https://github.com/coala/coala-bears/issues/906
> InvalidLinkBear: Remove FTP from regex

- README.rst
Remove 'Authors' section which is duplicated.
Closes https://github.com/coala/coala-bears/issues/918
> README: Remove duplicated 'Authors' section

- bears/dart/DartLintBear.py
- tests/dart/DartLintBearTest.py
As pointed out here https://github.com/dart-lang/dart_style/issues/261
dartanalyzer only supports indentation using 2 spaces. This commit
changes DartLintBear to check that use_spaces is True and
indent_size is 2 and raises a ValueError if not.
Fixes https://github.com/coala/coala-bears/issues/897
> DartLintBear: check settings validity

- bears/vcs/git/GitCommitBear.py
- tests/vcs/git/GitCommitBearTest.py
Fixes: https://github.com/coala/coala-bears/issues/942
> GitCommitBear: Print match regex with the message

- bears/yml/YAMLLintBear.py
- tests/yml/YAMLLintBearTest.py
Disable YAMLLint rule `document-start` by default because
many YAML files have no need for start and end markers, but
user still can enable it by using `document_start=true`
setting.
Add unit tests for YAMLLintBear.
Closes https://github.com/coala/coala-bears/issues/923
> YAMLLintBear: Disable `document-start` rule by default

- bears/vcs/git/GitCommitBear.py
Change docstring to use 'return' instead of 'returns'.
Fixes #571
> GitCommitBear.py: Rename param in docstring

- bears/java/CheckstyleBear.py
- tests/java/CheckstyleBearTest.py
Closes https://github.com/coala/coala-bears/issues/898 ensuring that if the checkstyle_config is google, then use_spaces has to be true and indent_size is 2.
> CheckstyleBear: Add invalid configuration check

- bears/yml/YAMLLintBear.py
Corrected the argument at line 53 from ``--config`` to ``--config-file``
Fixes https://github.com/coala/coala-bears/issues/979
> YAMLLintBear.py: Correct argument "--config"

- .ci/deps.sh
- bears/natural_language/LanguageToolBear.py
- requirements.txt
A lot of people are struggling because we actually require java to
install coala-bears. That sucks. Let's rather have this one bear not
work by default than all of those users giving up on the whole tool.
We can even have a nice message.
> Do not require language_check for coala-bears

- bears/general/AnnotationBear.py
- tests/general/AnnotationBearTest.py
Fixes https://github.com/coala/coala-bears/issues/993
> AnnotationBear: Use unescaped_search_for

- bears/python/PycodestyleBear.py
- tests/python/PycodestyleBearTest.py
A wrapper for `pycodestyle` formerly known
as `pep8`.
Closes https://github.com/coala/coala-bears/issues/986
> New Bear: PycodestyleBear

- bears/python/PyUnusedCodeBear.py
- tests/python/PyUnusedCodeBearTest.py
Add unused import check for builtin modules. 
Closes https://github.com/coala/coala/issues/2994
> PyUnusedCodeBear: Add unused import check

- bears/general/AnnotationBear.py
- tests/general/AnnotationBearTest.py
Right now AnnotationBear searches 1 position after annotation
which caused problems in
tests/c_languages/codeclone_detection/ClangASTPrintBearTest.py
and
tests/general/QuotesBearTest.py
Fixes https://github.com/coala/coala-bears/issues/1006
> AnnotationBear: Search after annotation length

- bears/rest/RSTcheckBear.py
- requirements.txt
- tests/rest/RSTcheckBearTest.py
Adds a bear for https://pypi.python.org/pypi/rstcheck to check
reStructuredText.
Closes https://github.com/coala/coala-bears/issues/902
> bears/rest: Add rstcheckerBear

- bears/java/CheckstyleBear.py
- tests/java/CheckstyleBearTest.py
The google and sun rules are provided in the jar,
and those rules are known to be compatible with the jar version.
Fixes https://github.com/coala/coala-bears/issues/1017
Fixes https://github.com/coala/coala-bears/issues/1034
> CheckstyleBear: Load google and sun rules from jar

- requirements.txt
pyflakes is not used directly by the bears.
It is indirectly used by autoflake, which
requires pyflakes>=0.8.1
Reverts e92774f0
> Remove explicit pyflakes requirement

- RELEASE_NOTES.rst
This file was missing a newline at line 113, which caused a unexpected indentation error in the sublist.
Fixes https://github.com/coala/coala-bears/issues/1052
> RELEASE_NOTES.rst: Fix newline error

- tests/generate_packageTest.py
Made the bad bear(empty file) in the test conform
to the glob that generate_package.py matches to
locate bears to allow it to test the empty bear branch.
Fixes https://github.com/coala/coala-bears/issues/1055
> generate_packageTest.py: Fix NoBearPath to conform with glob

- tests/generate_packageTest.py
**Backport**
Made the NoBearPath(empty file) in the test conform
to the glob that generate_package.py matches to
locate bears to allow it to test the empty bear branch.
Fixes https://github.com/coala/coala-bears/issues/1055
> 0.9_test_fix backport to 0.9

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
Add pip vcs url parser in InvalidLinkBear, so InvalidLinkBear
now can detects some pip vcs urls without 'Broken link' warning.
Closes https://github.com/coala/coala-bears/issues/1009
> InvalidLinkBear: Add pip vcs url parser

- tests/general/InvalidLinkBearTest.py
Fix useless testcase in InvalidLinkBearTest.py, especially
for `invalid_file` testcase by adding loop.
Closes https://github.com/coala/coala-bears/issues/1063
> InvalidLinkBearTest: Fix useless testcase

- bears/python/YapfBear.py
This removes check_prerequisites that was not needed as bears already checks for python ver 3.4+
Closes https://github.com/coala/coala-bears/issues/928
> YapfBear.py : Delete check_prerequisites method

- tests/general/AnnotationBearTest.py
Removed an unwanted space in the import statement that imports HiddenResult.
Closes https://github.com/coala/coala/issues/3153
> AnnotationBearTest.py: Remove an extra space

- requirements.txt
This dependency is already managed by the coala package.
Due to continuous integration coala and coala-bears installing the
latest master of the other package, it can not be modified if it
appears in both otherwise a pkg_resources.ContextualVersionConflict
is raised when it is used.
Fixes https://github.com/coala/coala-bears/issues/1110
> Remove libclang-py3 from requirements.txt

- .ci/deps.sh
- circle.yml
precise hlint is 1.8.24, which isnt usable as --json was added
in version 1.9.1.
The build script currently installs precise hlint, and then replaces
it with a seemingly custom .deb of 1.9.26.
The trusty hlint is 1.8.54, however xenial hlint is 1.9.26,
so it can be installed using apt-get on the trusty image.
Also move the .deb save location to ~/.apt-cache, with the
other cached .debs.
> CircleCI: Do not install precise hlint

- bears/python/YapfBear.py
YAPFBear, ``space_between_ending_comma_and_closing_bracket`` has a default
of ``false``, whereas the upstream YAPF setting has a default of ``true``.
Fixes coala/coala#3241
> YAPFBear: Make default settings similar to upstream

- .travis.yml
gfortran was accidentally removed in the last iteration
of 3df3defa9, and not noticed due to caching.
Fixes https://github.com/coala/coala-bears/issues/1144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coala/coala-bears/1146)
> .travis.yml: Add gfortran to pre-install packages

- .ci/deps.sh
Replace install.packages parameter `dependencies=True` with
only 'Depends'.
The default, `NA`, means `c("Depends", "Imports", "LinkingTo")`,
while `True` also includes `"Suggests"`.
Those options allow running examples, tests and vignettes, which
are not necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coala/coala-bears/1121)
> deps.sh: Do not install suggested packages for R

- .ci/deps.sh
- .travis.yml
- circle.yml
The install.sh provided by tailor installs into /usr/local,
which is not cachable and requires sudo.
Revise the install.sh to install with a PREFIX of ~/.local/,
which places everything into ~/.local/tailor/, with the
version specific components in ~/.local/tailor/tailor-1.9.x/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coala/coala-bears/1142)
> deps.sh: Cache installed tailor

- tests/cmake/CMakeLintBearTest.py
- tests/general/AnnotationBearTest.py
- tests/general/IndentationBearTest.py
- tests/general/QuotesBearTest.py
- tests/java/CheckstyleBearTest.py
- tests/js/JSComplexityBearTest.py
- tests/js/JSHintBearTest.py
- tests/js/JSONFormatBearTest.py
- tests/natural_language/LanguageToolBearTest.py
- tests/python/requirements/PySafetyBearTest.py
- tests/scala/ScalaLintBearTest.py
Remove the unused imports in tests directory,
to help prepare for coala/coala#3066
Fixes https://github.com/coala/coala-bears/issues/1126
> tests: Remove unused import statements

- bears/natural_language/AlexBear.py
The docstring mentions that you should
use only Englis language.
It also includes a link to Alex for
instructions and tests.
Fixes https://github.com/coala/coala-bears/issues/1138
> AlexBear.py: Change AlexBear docstring

- bears/csv/CSVLintBear.py
- tests/csv/CSVLintBearTest.py
Updates Regex to match better to csvlint output in order to
get Line and the erroneous text.
Adjusts Severity Map as per docs.
(https://github.com/theodi/csvlint.rb/blob/master/README.md)
Closes https://github.com/coala/coala-bears/issues/967
> CSVLintBear: Get Line and Error column of the issue

- .coafile
No more broken pypi readmes!
Closes https://github.com/coala/coala-bears/issues/1177
> .coafile: Enable reSTCheckbear on README.rst

- .ci/deps.sh
- .travis.yml
espeak is an optional dependency of PyPrint, which
is not used by coala-bears.
Closes https://github.com/coala-analyzer/coala/issues/1939
> CI: Remove espeak

- tests/BearTestHelper.py
- tests/c_languages/ClangComplexityBearTest.py
- tests/c_languages/codeclone_detection/ClangASTPrintBearTest.py
- tests/c_languages/codeclone_detection/ClangCloneDetectionBearTest.py
- tests/dart/DartLintBearTest.py
- tests/general/CPDBearTest.py
- tests/java/CheckstyleBearTest.py
- tests/natural_language/AlexBearTest.py
- tests/natural_language/LanguageToolBearTest.py
- tests/python/MypyBearTest.py
- tests/python/YapfBearTest.py
- tests/vcs/git/GitCommitBearTest.py
This change removes tests/BearTestHelper.py
and it's usage in importing in other
test files
Fixes #1195
> tests: Removes deprecated tests.BearTestHelper

- .coafile
This forces developers to write proper rst files
Closes https://github.com/coala/coala-bears/issues/1182
Related to https://github.com/coala/coala/issues/3044
> .coafile: Enable reSTCheckBEar on all rst files

- bears/__init__.py
The logic in d5f0982 to prevent installation on Python 3.3
was incorrect as Version 3.3.1 is greater than Version 3.3,
so only 3.3.0 was rejected by the current logic.
Fixes https://github.com/coala/coala/issues/3310
> assert_supported_version: Reject Python 3.3.x

- .travis.yml
Activates a build on Python 3.6 which previously didn't existed.
Closes https://github.com/coala/coala-bears/issues/1170
> .travis.yml: Adds build on Python 3.6-dev

- tests/c_languages/ClangComplexityBearTest.py
I have replaced assertRaises() with assertRaisesRegex() for the ClangComplexityBearTest script
Done as a part of GCI, [link to GCI Task](https://codein.withgoogle.com/dashboard/task-instances/6223930375274496/)
Fixes a part of #1194
[There are 6 cases to be replaced, 1 was done by @jayvdb and this would be the next one.]
[I am only doing one because, I want more of you guys to code for it and the GCI task does'not allow me too.]
So please review and merge guys happy coding :)
> ClangComplexityBearTest.py: Change `assertRaises()`

- tests/dart/DartLintBearTest.py
`assertRaisesRegex` is used over `assertRaises` to validate the error
message to confirm the type of error that occured during execution.
Related to https://github.com/coala/coala-bears/issues/1194
> DartLintBearTest: Use `assertRaisesRegex` to validate returned error

- bears/markdown/MarkdownBear.py
- package.json
- tests/markdown/MarkdownBearTest.py
New parameter to enforce maximum allowed line length.
Closes https://github.com/coala/coala-bears/issues/1181
> MarkdownBear: Add setting to enforce maximum line length

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
Increase default_timeout value to 15. Change corresponding values in
test file (InvalidLinkBearTest.py) to 15 as well
Fixes https://github.com/coala/coala-bears/issues/1219
Additional:
> InvalidLinkBear.py: Increase default_timeout value

- requirements.txt
dependency_management is already required by coala,
and the versions required are now out of sync.
> requirements.txt: Remove dependency_management

- bears/python/PycodestyleBear.py
- requirements.txt
PycodestyleBear was added (90043806) without an explicit
entry in requirements.txt, so it inherited the requirement
pycodestyle>=2.2 from autopep8.
> PycodestyleBear: Require pycodestyle 2.2

- .ci/generate_bear_requirements.py
- bear-requirements.txt
- bears/python/PyFlakesBear.py
- bears/python/RadonBear.py
radon 1.4.2 added a dependency on flake8-polyfill, which depends
on flake8 without any version specification, and flake8 versions
have various version dependencies on pyflakes and pycodestyle.
As a result, it is not possible to know what versions of pyflakes
and pycodestyle that will be required to be compatible with
whatever flake8 version happens to be installed.
Fixes https://github.com/coala/coala-bears/issues/1228
> RadonBear: Pin to version 1.4.0

- bears/python/RadonBear.py
- requirements.txt
coala-bears 0.9 should not be used with coala 0.10
> requirements: Require coala 0.9.1+

- bears/general/KeywordBear.py
- tests/general/KeywordBearTest.py
Ensures that keywords within a file can be matched against
a user defined regex. A testcase is also added in KeywordBearTest.py
for this feature.
Closes https://github.com/coala/coala-bears/issues/311
> KeywordBear.py: Add optional regex_keyword param

- .ci/generate_bear_requirements.py
- bear-requirements.txt
- bears/gettext/DennisBear.py
coala builds are currently failing. This is a hotfix. We should revert
this when https://github.com/willkg/dennis/issues/91 gets resolved or
alternatively remove DennisBear.
> requirements.txt: Add click 6.6

- bears/general/KeywordBear.py
- tests/general/KeywordBearTest.py
Output appropriate message if the language given in input is not valid/not supported for KeywordBear
Fixes https://github.com/coala/coala-bears/issues/1256
> KeywordBear.py: Output appropriate message

- bears/general/AnnotationBear.py
Changes the four occurences of contatining into containing, in
the docstring of function find_annotation_ranges.
Fixes https://github.com/coala/coala-bears/issues/1293
> AnnotationBear.py: Corrects typo in docstring

- tests/markdown/MarkdownBearTest.py
A better test for MarkdownBear to check the exact message
of the result for a maximum line length error.
Related to https://github.com/coala/coala-bears/issues/1235
>   MarkdownBear: Add test to check message for error 

- .ci/deps.sh
- bears/haskell/GhcModBear.py
- tests/haskell/GhcModBearTest.py
Add a new bear in Haskell, namely GhcModBear for syntax checking.
Closes https://github.com/coala/coala-bears/issues/297
> bears/haskell: Add GhcModBear for syntax checking

- .ci/appveyor.yml
This line was copied from coala in 6875fad64
but it is no longer required.
> AppveyorCI: Remove astroid upgrade as not required

- .travis.yml
Turns the travis builds off for branch 'sils/*'
to prevent redundant builds.
Closes https://github.com/coala/coala-bears/issues/1285
> .travis.yml: Exclude branch 'sils/*'

- test-requirements.txt
Coverage should have been ~= to 4.2.0, not 4.2
Fixes https://github.com/coala/coala-bears/issues/1316
> test-requirements.txt: Fix coverage pin

- bears/haskell/HaskellLintBear.py
- tests/haskell/HaskellLintBearTest.py
Add multiple line diff message to be handled properly, atleast
when only the first line of `hlint` output is different (which is the
case in most cases)
Closes https://github.com/coala/coala-bears/pull/1276
> HaskellLintBear.py: Add multiple line diff message workaround

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
Resolve matching for url of type ```[valid_url](valid_url)```
Fixes https://github.com/coala/coala-bears/issues/1338
> InvalidLinkBear: Support markdown files

- .coafile
- bears/vcs/git/GitCommitBear.py
- tests/vcs/git/GitCommitBearTest.py
Force body to follow a certain multiline pattern
Fixes #1331
> GitCommitBear.py: Enforce fullmatch on body_regex

- .ci/generate_bear_requirements.py
- bear-requirements.txt
- requirements.txt
List inherited packages in requirements.txt, and
update generate_bear_requirements to not repeat
those packages in bear-requirements.
Use this to avoid adding requests to bear requirements.txt
Also fix requirement in InvalidLinkBear to match
requests version used by coala.
> bear-requirements.txt: Omit inherited dependencies

- .ci/deps.sh
Do not re-install ghc-mod from source
if it has already been cached.
Related to https://github.com/coala/coala-bears/issues/297
> .ci/deps.sh: Use cached ghc-mod

- requirements.txt
coala now has Maven Requirement and
is_installed() function for Distribution
Requirement, So changed version to
0.10.0.dev20170127183105
Closes https://github.com/coala/coala-bears/issues/1251
> requirements.txt: Fixed coala version

- .coafile
- tests/vcs/git/GitCommitBearTest.py
coafile: Rename body_close_issue_last_line
Renamed `body_close_issue_last_line` to `body_close_issue_on_last_line`
Fixes #1362
> coafile: Rename 'body_close_issue_last_line to body_close_issue_on_last_line'.

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
The InvalidLinkBear should analyze all the links
in a line instead of just analyzing the first one.
Fixes https://github.com/coala/coala-bears/issues/1296
> InvalidLinkBear: Multiple links

- .ci/deps.sh
Reduce the length of output in ci
log by removing download progress
information
Closes https://github.com/coala/coala-bears/issues/1123
> deps.sh: Reduce the length of output

- bears/vcs/git/GitCommitBear.py
Fixes https://github.com/coala/coala-bears/issues/1217
> GitCommitBear.py: Change regex to shortlog_regex

- .ci/deps.sh
Installing apt package 'golang' installs 'golang-doc',
for documentation, which is not needed.
Installing the golang-go package also installs 'golang-src'
but omits golang-doc.
them. …
> .ci/deps.sh: Do not install go documentation

- bears/python/PycodestyleBear.py
Fixes https://github.com/coala/coala-bears/issues/1393
> PycodestyleBear.py: Remove extra "'" from message

- bears/yaml/YAMLLintBear.py
- tests/yaml/YAMLLintBearTest.py
Some projects use documents starts (`---`) in YAML documents (for example Ansible, OpenStack, yamllint), others don't. Since these markers are required when declaring multiple documents in a single .yaml file (see [the spec](http://yaml.org/spec/1.2/spec.html#id2800132)), it is a bad idea to forbid them.
This commit disables the `document-start` rule by default, instead of forcing / forbidding the use of these markers.
Closes: #1417
Fixes: #923 #965
> yamllint: Disable `document-start` by default

- bears/python/PyDocStyleBear.py
- tests/python/PyDocStyleBearTest.py
It adds two new parameters for the bear
`pydocstyle_add_ignore` and `pydocstyle
_add_select`. It also improves the param
definition of `ignore`. Earlier,
conflicting checks were getting enabled
due to misuse of `ignore`.
Fixes https://github.com/coala/coala-bears/issues/1345
them.
likely receive a lot of bot comments and build …
> PyDocStyleBear.py: Add new parameters

- bears/perl/PerlCriticBear.py
PerlCriticBear: Simplify the linter executable
The change made in PerlCriticBear.py
is to simplify the linter by
removing the 'if' condition.
Fixes https://github.com/coala/coala-bears/issues/1389
them. …
> PerlCriticBear.py:  Simplify the linter executable

- bears/js/JSONFormatBear.py
- tests/js/JSONFormatBearTest.py
This change parses the default exception message to print
only 'Expecting property name enclosed in double quotes.'
instead of 'Expecting property name enclosed in double
quotes: line 2 column 7 (char 8)'.It also shows line and
column where the error is raised.
Closes https://github.com/coala/coala-bears/issues/35
them.
likely …
> JSONFormatBear: Parse Exception message

- Gemfile
- bears/java/CheckstyleBear.py
- bears/perl/PerlCriticBear.py
- bears/php/PHPLintBear.py
- bears/ruby/RubySyntaxBear.py
- bears/scala/ScalaLintBear.py
- bears/xml2/XMLBear.py
~~DO NOT MERGE.~~
~~This should be merged after https://github.com/coala/coala-bears/pull/1386 ~~
(1386 is going to take a while, and we need these in to assist with understanding needed Requirements)
> DistributionRequirement enhancements

- .ci/deps.sh
The packages installed on the Circle trusty image with
Ubuntu xenial to install php-codesniffer cause unmet dependencies.
Fixes https://github.com/coala/coala-bears/issues/1433
> CircleCI: Add Ubuntu package php7.0-cli to trusty

- bears/markdown/MarkdownBear.py
- package.json
Use remark-lint 5.4 if available.
Fixes https://github.com/coala/coala-bears/issues/1444
> MarkdownBear: Restrict remark-lint to ~5

- MANIFEST.in
bear-requirements.txt is used by setup.py and
requirements.txt
Fixes https://github.com/coala/coala-bears/issues/1448
> MANIFEST.in: Add bear-requirements.txt

- .travis.yml
Python version `3.6-dev` is confusing, as Python 3.6 has been
officially released.
Also remove unnecessary nvm commands.
> .travis.yml: Use Python version '3.6'

- .ci/generate_bear_requirements.py
- bears/java/CheckstyleBear.py
- bears/yaml/RAMLLintBear.py
- package.json
Workarounds for https://github.com/coala/coala-bears/issues/1461 and https://github.com/coala/coala-bears/issues/1470 .
> Temporary fixes for CheckstyleBear & RamllintBear

- .ci/deps.sh
The main repository deleted gotype in
https://github.com/golang/tools/commit/f5a6ee1e
As the coala-bears builds depend on fetching a working gotype,
fork https://github.com/jayvdb/gotype has been created and used.
Fixes https://github.com/coala/coala-bears/issues/1472
them.
likely receive a lot of bot comments and build failures if …
> .ci/deps.sh: Use fork of gotype

- bears/r/FormatRBear.py
- tests/r/FormatRBearTest.py
r_keep_comments,r_keep_blank_lines,r_braces_on_next_line,r_use_arrows are
disabled and will not be checked untill the user provides value.
closes https://github.com/coala/coala-bears/issues/514
> FormatRBear.py: disable parameter-options

- .ci/appveyor.yml
Exclude only branch 'sils/*'.
Closes https://github.com/coala/coala-bears/issues/1285
Related to https://github.com/coala/coala/issues/3664
> AppVeyor CI: Allow builds on forks

- bears/java/CheckstyleBear.py
- tests/java/CheckstyleBearTest.py
The geosoft ruleset last worked with checkstyle 4.4.
Fixes https://github.com/coala/coala-bears/issues/1463
> CheckstyleBear: Remove geosoft ruleset

- .ci/deps.sh
- .travis.yml
- bears/general/LicenseCheckBear.py
- tests/general/LicenseCheckBearTest.py
- tests/general/licensecheck_test_files/apache_license_without_copyright.py
- tests/general/licensecheck_test_files/copyright_without_license.py
- tests/general/licensecheck_test_files/mit_license.py
- tests/general/licensecheck_test_files/no_license.py
Closes https://github.com/coala/coala-bears/issues/823
them.
instead. …
> bears/general: Add LicenseCheckBear

- coala-bears.cabal
cmdargs==0.10.15 requires Cabal 1.18, which is not
available on all CI workers.
Fixes https://github.com/coala/coala-bears/issues/1508
> coala-bears.cabal: Pin cmdargs==0.10.14

- .ci/deps.coala-bears.sh
- .ci/deps.sh
- .travis.yml
- circle.yml
Download checkstyle and scalastyle jar files before running tests on Travis and AppVeyor.
> CI: Fetch coala-bears dependency files

- .travis.yml
Avoid installation of mypy-lang and install 3to2 early
as it is needed by guess-language and language-check
as they do not install cleanly on Python 2 without it.
Avoid compilation of Python modules to avoid Python 3
syntax errors in build logs.
Places jobs for unsupported Python versions after the
supported versions, so newcomers dont read those first.
Related to https://github.com/coala/coala/issues/3310
Related to https://github.com/coala/coala/pull/3614
> .travis.yml: Test version check on Python 2.7

- bears/natural_language/LanguageToolBear.py
- tests/natural_language/LanguageToolBearTest.py
Rename setting `language` to `natural_language`
in LanguageToolBear.py to resolve conflict
Closes https://github.com/coala/coala-bears/issues/1137
> LanguageToolBear.py: Resolve settings conflict

- .ci/appveyor.yml
- .gitattributes
- bears/java/CheckstyleBear.py
- tests/java/CheckstyleBearTest.py
Since 9227382, errors from checkstyle were ignored.
Also set java files to be native EOL in .gitattributes,
to match default EOL expected by Checkstyle rule
NewlineAtEndOfFile.
Fixes https://github.com/coala/coala-bears/issues/1464
> CheckstyleBear: Detect errors

- bears/shell/ShellCheckBear.py
- tests/shell/ShellCheckBearTest.py
This extend the ShellCheckBear to use **ignore rules** feature provided by shellcheck, see
https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-errors-in-one-specific-run
The commandline argument for ignoring rules is `-e SCXXX1,SCXXX2,SCXXX3`
Closes https://github.com/coala/coala-bears/issues/1329
> ShellCheckBear: Add option to ignore specific rules

- bears/general/InvalidLinkBear.py
- tests/general/InvalidLinkBearTest.py
Reduces the severity of the XML namespaces which are
present in xmlns attributes of the file. If the
same namespace link occurs more than once in the file,
it should not be reported.
Closes https://github.com/coala/coala-bears/issues/1239
> InvalidLinkBear: Reduce severity

- bears/java/CheckstyleBear.py
checkstyle 6.19 is the last release in the 6.x
series, fixing many bugs in 6.15 which coala
has been using.
Fixes https://github.com/coala/coala-bears/issues/1465
> CheckstyleBear: Upgrade checkstyle to 6.19

- tests/python/pyroma_test_files/complete/complete/__init__.py
The print call in the pyroma_test_files complate package ``__init__``
is unnecessary for the test, and causes unexpected output when a test
runner such as ``green`` collects ``test_*.py`` by default.
Fixes https://github.com/coala/coala-bears/issues/1594
> pyroma_test_files: Remove unnecessary print

- bears/__init__.py
- tests/coalaBearTest.py
Print a warning if the installed version of coala is not 
same with coala-bears.
Closes https://github.com/coala/coala/issues/3042
> bears/__init__.py: Check version with coala core

- bears/python/PyUnusedCodeBear.py
- tests/python/PyUnusedCodeBearTest.py
Fix #1584 pass remove_unused_variables explicitely
to the run() method and add the corresponsing
doc string
them. …
> PyUnusedCodeBear: Implement remove_unused_variables

- bears/generate_package.py
- tests/generate_packageTest.py
generate_package assumes it is in the parent directory
of the bears.
Fixes https://github.com/coala/coala-bears/issues/1603
> generate_package.py: Run in bears parent directory

- bears/markdown/MarkdownBear.py
The introduction of max_line_length with a default of 80
was a breaking change as previously line length was not
constrained.
This constraint required the use of remark-lint, which
caused MarkdownBear to remove all content from files
if remark-lint could not be found in NODE_PATH.
The default is now again to not check line length,
and not use remark-lint unless the .coafile explicitly
requests a max_line_length.
Fixes https://github.com/coala/coala-bears/issues/1581
> MarkdownBear: Set max_line_length default to None

- .ci/deps.sh
- .travis.yml
- bears/php/PHPMessDetectorBear.py
- circle.yml
- tests/php/PHPMessDetectorBearTest.py
- tests/php/phpmessdetector_test_files/cleancode_violation.php
- tests/php/phpmessdetector_test_files/codesize_violation.php
- tests/php/phpmessdetector_test_files/design_violation.php
- tests/php/phpmessdetector_test_files/naming_violation.php
- tests/php/phpmessdetector_test_files/unusedcode_violation.php
Closes https://github.com/coala/coala-bears/issues/22
them.
instead. …
> bears/php: Add PHPMessDetectorBear

- requirements.txt
Upgrade to latest pre-release build of coala,
which includes dependency_management 0.4.
Related to https://github.com/coala/coala/issues/4064
> requirements.txt: Use dependency_management 0.4

- bears/python/PyImportSortBear.py
- tests/python/PyImportSortBearTest.py
Added a missing parameter known_third_party to isort
function. It was being passed to run function but
was missing in wrapper.
Fixes https://github.com/coala/coala-bears/issues/1510
> PyImportSortBear.py: Add missing parameter

- bears/ruby/RubySyntaxBear.py
Add ``CondaRequirement`` for the ``ruby`` package and add
``AnyOneOfRequirements`` to combine multiple requirements,
returning ``true`` if any one of them is installed, both being
supported by ``dependency_management`` 0.4.0
Closes https://github.com/coala/coala-bears/issues/1656
them.
likely receive a lot of bot comments and build …
> RubySyntaxBear: Add ``CondaRequirement``

- bears/general/KeywordBear.py
- tests/general/KeywordBearTest.py
If a setting is used in the coafile and nothing is assigned, then the
value of that key is an empty string ''. Now, since `keywords` is a
`list`, `list('')` returns an empty list: `[]` which leads to
construction of regex `r'()'` which matches every character, and hence
produces false results.
Fixes https://github.com/coala/coala-bears/issues/1689
them.
our bot will still report the issues for the …
> KeywordBear: Do not run if `keywords` is empty

- bears/general/KeywordBear.py
- tests/general/KeywordBearTest.py
If setting keyword is used in coafile and not assigned, then keywords
is an empty list, which leads to construction of regex `r'()'` which
matches all the letters, hence yielding false results.
Fixes https://github.com/coala/coala-bears/issues/1689
them.
pass …
> KeywordBear: Handle empty keywords

- .ci/deps.sh
- bears/configfiles/TOMLBear.py
- tests/configfiles/TOMLBearTest.py
This bear uses gotoml to know the type of every key used in a file.
Closes https://github.com/coala/coala-bears/issues/1375
> Add TOMLBear

- bears/python/PyImportSortBear.py
- tests/python/PyImportSortBearTest.py
If this option is set, then the imports separated by a line will be
fed independently to the SortImports function and the results will be
yielded accordingly.
Fixes https://github.com/coala/coala-bears/issues/879
> PyImportSort: Option to treat imports separately

- bears/scss/SCSSLintBear.py
The results currently have the column number as the line number.
Fixes https://github.com/coala/coala-bears/issues/1742
> SCSSLintBear: Fix result line numbers

- .ci/deps.apt.sh
- .ci/deps.java.sh
- .ci/deps.opam.sh
- .ci/deps.pip.sh
- .ci/deps.r.sh
- .ci/deps.sh
- .travis.yml
- circle.yml
Splitting deps.sh allows the time to complete to be measured by
the CI systems, indicating where build times can be improved.
> deps.sh: Split into smaller files

- .ci/appveyor.yml
- .ci/deploy.coverage.sh
- .travis.yml
- circle.yml
- test-requirements.txt
Currently codecov-bash is used, which involves an uncached fetch
of a unversioned bash script.
Using codecov-python allows the tool to be cached, and greater
reliability due to versioned releases of the tool.
In addition, codecov-bash does not work on Windows, and our
developer base is better tuned to investigate any python
related problems.
Fixes https://github.com/coala/coala/issues/3718
Related to https://github.com/coala/coala-bears/issues/1415
> Use codecov-python

- .ci/tests.sh
- bear-requirements.txt
- bears/vimscript/VintBear.py
The bear is broken, and it breaks all coala, due to
its requirement chardet~=2.3.0 which is incompatible
with requests adding requirement chardet~=3.0.2.
Related to https://github.com/coala/coala-bears/issues/1785
> VintBear: Deactivate bear

- bears/stylus/StylintBear.py
- package.json
- tests/stylus/StylintBearTest.py
- tests/stylus/stylint_test_files/.stylintrc
- tests/stylus/stylint_test_files/test_bad_alphabetical_order.styl
- tests/stylus/stylint_test_files/test_bad_brackets.styl
- tests/stylus/stylint_test_files/test_bad_duplicates.styl
- tests/stylus/stylint_test_files/test_bad_missing_colon.styl
- tests/stylus/stylint_test_files/test_bad_mixed_spaces_tabs.styl
- tests/stylus/stylint_test_files/test_bad_no_important.styl
- tests/stylus/stylint_test_files/test_bad_semicolon.styl
- tests/stylus/stylint_test_files/test_bad_trailing_whitespace.styl
- tests/stylus/stylint_test_files/test_valid_file.styl
Closes https://github.com/coala/coala-bears/issues/754
them.
instead. …
> bears/stylus: Add StylintBear

- bears/stylus/StylintBear.py
- tests/stylus/StylintBearTest.py
- tests/stylus/stylint_test_files/test_bad_placeholder_space_color.styl
Use the implemented settings to generate a `config_file` and use
that file if the user does not explicitly mention `stylint_config`.
Closes https://github.com/coala/coala-bears/issues/1795
them.
After you submit your pull request, …
> StylintBear: Implement settings

- bears/documentation/DocumentationStyleBear.py
- tests/documentation/DocumentationStyleBearTest.py
- tests/documentation/test_files/DocumentationStyleBear/bad_file.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file2.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file2.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file3.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file3.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file4.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file4.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file5.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file5.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/good_file.py.test
- tests/documentation/test_files/DocumentationStyleBear/good_file2.py.test
- tests/documentation/test_files/DocumentationStyleBear/good_file3.py.test
Continues https://github.com/coala/coala-bears/pull/699
them.
instead. …
> Add DocumentationStyleBear

- bears/python/PycodestyleBear.py
Use 'typed_list(str)' instead of plain str
Closes https://github.com/coala/coala-bears/issues/1739
them. …
> PycodestyleBear.py: Use 'typed_list(str)'

- bears/ruby/RuboCopBear.py
Generation of `config_file` is only done if `rubocop_config` is
absent as an argument. This is a performance gain since
`config_file` was generated irrespective of `rubocop_config`,
each time the bear was run.
Closes https://github.com/coala/coala-bears/issues/1839
them.
likely receive a lot of bot comments and build failures if …
> RubocopBear: Optional generation of `config_file`

- .ci/deps.pip.sh
- .rultor.yml
- .travis.yml
The docker `coala/rultor-python` installs `pip3`.  If it doesnt,
something larger has failed and installing pip3 isnt going to help.
Related to https://github.com/coala/coala/issues/4393
Fixes https://github.com/coala/coala-bears/issues/1853
> .rultor.yml: Do not install pip3

- bears/documentation/DocumentationStyleBear.py
`TextPosition` is now accepted by
`DocumentationComment` instead of `range`.
Closes https://github.com/coala/coala-bears/issues/1857
them.
When asked …
> DocumentationStyleBear.py: Change `range` to `postion`

- Gemfile
- bears/yaml/TravisLintBear.py
- tests/yaml/TravisLintBearTest.py
- tests/yaml/travislint_test_files/.bad_travis.yml
- tests/yaml/travislint_test_files/.good_travis.yml
Closes https://github.com/coala/coala-bears/issues/294
them.
instead. …
> bears/yaml: Add TravisLintBear

- Gemfile
- bears/ruby/RuboCopBear.py
- tests/ruby/RuboCopBearTest.py
- tests/ruby/test_files/bad_file.rb
- tests/ruby/test_files/good_file.rb
- tests/ruby/test_files/indent_file.rb
https://github.com/bbatsov/rubocop/pull/4226 indicates that `--stdin`
takes filename as an argument which was incorporated. Also, the tests
were enhanced that involved the bear to be run on files with the `.rb`
(ruby) extension because initially the bear was run on the generated
temporary files that was the cause of error.
Fixes https://github.com/coala/coala-bears/issues/1548
them.
our bot will still …
> RuboCopBear: Fix CI breakage

- bears/general/URLBear.py
- tests/general/URLBearTest.py
Create URLResult in URLBear.py and replace HiddenResult
with URLResult, so other bears which depends on this bear
can fetch the value through attributes instead of `contents`.
Closes https://github.com/coala/coala-bears/issues/1902
them.
pass on every single …
> URLBear: Create URLResult

- bears/markdown/MarkdownBear.py
Replace `markdown_horizontal_rule` in the docstring by
`horizontal_rule` which is used `create_arguments(...)`.
Closes https://github.com/coala/coala-bears/issues/1907
them. …
> MarkdownBear: Replace `markdown_horizontal_rule`

- bears/general/CPDBear.py
- tests/general/CPDBearTest.py
Replace “pragma: no cover” with test for unsupported language
Closes https://github.com/coala/coala-bears/issues/1708
them. …
> CPDBear: Add test for unsupported language

- bears/css/StyleLintBear.py
- circle.yml
- docs-requirements.txt
- requirements.txt
According to https://github.com/coala/coala/pull/4330 and https://github.com/coala/coala/pull/4333
Partial continuation of https://github.com/coala/coala-bears/pull/1569
Closes https://github.com/coala/coala-bears/issues/1554
Fixes https://github.com/coala/coala-bears/issues/1821 as side-effect
And changes `circle.yml` to use Python 3.4.3 for building docs instead of default 3.5.1, since the latter's `typing` package causes recent `sphinx` versions to fail
> Use sphinx-1.6.2 for building docs and avoid warnings by cleaning up output_regex of StyleLintBear

- bears/markdown/MarkdownBear.py
- package.json
- tests/markdown/MarkdownBearTest.py
Closes https://github.com/coala/coala-bears/issues/924
them.
instead. …
> MarkdownBear: Add `validate-links` plugin

- ignore.txt
- setup.py
@NiklasMM if this is good to you you'll wanna add it to your cherry PR :)
> setup: Ignore lxml on avg installation

- .ci/deps.sh
- bears/c_languages/ArtisticStyleBear.py
- tests/c_languages/ArtisticStyleBearTest.py
Closes https://github.com/coala/coala-bears/issues/388
them.
instead. …
> bears/c_languages: Add ArtisticStyleBear

- bears/documentation/DocumentationStyleBear.py
- requirements.txt
DocumentationStyleBear uses DocBaseClass.
Closes https://github.com/coala/coala-bears/issues/1927
them. …
> DocumentationStyleBear: Use DocBaseClass

- bears/documentation/DocumentationStyleBear.py
- tests/documentation/DocumentationStyleBearTest.py
- tests/documentation/test_files/DocumentationStyleBear/bad_file5.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file5.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/good_file3.py.test
Add expand_one_liners setting which will expand one
liners to multi line docstring.
Closes https://github.com/coala/coala-bears/issues/1856
them.
When …
> DocumentationStyleBear: Add expand_one_liners

- bears/apertium/ApertiumLintBear.py
The docstring for ApertiumLintBear settings contains incorrect
Unicode symbols, resulting in incorrect rendering and hidden
characters.
Fixes https://github.com/coala/coala-bears/issues/1877
> ApertiumLintBear: Remove wrong docstring unicode

- bears/markdown/MarkdownBear.py
- tests/markdown/MarkdownBearTest.py
Closes https://github.com/coala/coala-bears/issues/926
them.
instead. …
> MarkdownBear: Add `remark-lint` settings

- bears/css/CSSCombBear.py
- package.json
- tests/css/CSSCombBearTest.py
- tests/css/csscomb_test_files/.csscomb.json
Closes https://github.com/coala/coala-bears/issues/634
them.
instead. …
> bears/css: Add CSSCombBear

- bear-requirements.txt
- bears/hypertext/HTTPoliceLintBear.py
- tests/hypertext/HTTPoliceLintBearTest.py
- tests/hypertext/httpolice_test_files/test_bad_header.har
- tests/hypertext/httpolice_test_files/test_syntax_error_in_request_target.har
- tests/hypertext/httpolice_test_files/test_valid_file.har
Closes https://github.com/coala/coala-bears/issues/596
them.
instead. …
> bears/hypertext: Add HTTPoliceLintBear.py

- bears/vcs/git/GitCommitBear.py
NLTK data package maxent_treebank_pos_tagger is not used.
Closes https://github.com/coala/coala-bears/issues/1974
> GitCommitBear: Remove unnecessary tagger data

- bears/hypertext/HTMLHintBear.py
- package.json
- tests/hypertext/HTMLHintBearTest.py
- tests/hypertext/htmlhint_test_files/.htmlhintrc
- tests/hypertext/htmlhint_test_files/test_attribute_duplication.html
- tests/hypertext/htmlhint_test_files/test_bad_inline_style.html
- tests/hypertext/htmlhint_test_files/test_bad_lowercase_attribute.html
- tests/hypertext/htmlhint_test_files/test_bad_lowercase_tagname.html
- tests/hypertext/htmlhint_test_files/test_bad_tag_pair.html
- tests/hypertext/htmlhint_test_files/test_bad_unique_attribute_id.html
- tests/hypertext/htmlhint_test_files/test_doctype_at_beginning.html
- tests/hypertext/htmlhint_test_files/test_links_in_href.html
- tests/hypertext/htmlhint_test_files/test_require_alt_attribute.html
Add `HTMLHintBear` that was worked upon by @Asnelchristian.
This PR is a continuation of @Asnelchristian's PR with some
modifications.
Closes https://github.com/coala/coala-bears/issues/635
them.
After you submit your pull request, …
> bears/hypertext: Add HTMLHintBear

- bears/elm/ElmLintBear.py
- tests/elm/ElmLintBearTest.py
Remove `pragma: no cover` in `check_prerequisites` by adding
a suitable test.
Closes https://github.com/coala/coala-bears/issues/1996
Related to https://github.com/coala/coala-bears/issues/1618
them. …
> ElmLintBear: Remove `pragma: no cover`

- bears/documentation/DocGrammarBear.py
- tests/documentation/DocGrammarBearTest.py
This bear checks for spellings and grammatical mistakes
on the descriptions of documentation comments.
them. …
> Add DocGrammarBear for docstrings

- bears/yaml/TravisLintBear.py
- tests/yaml/TravisLintBearTest.py
Add a check for internet connection in the `check_prerequisites`
method without which the bear will fail to run.
Fixes https://github.com/coala/coala-bears/issues/1978
them. …
> TravisLintBear: Check for internet connection

- bears/documentation/DocumentationStyleBear.py
- requirements.txt
- tests/documentation/DocumentationStyleBearTest.py
DocStyleBear will use new error handling mechanism
`MalformedComment`. And yield a `RESULT` with a
message containing error details.
Related to https://github.com/coala/coala/issues/4548
them.
After you submit your pull request, …
> DocStyleBear: Add `MalformedComment` support

- bears/documentation/DocumentationStyleBear.py
- requirements.txt
- tests/documentation/DocumentationStyleBearTest.py
- tests/documentation/test_files/DocumentationStyleBear/bad_file.java.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file.java.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file2.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file2.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file3.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file3.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/bad_file4.py.test
- tests/documentation/test_files/DocumentationStyleBear/bad_file4.py.test.correct
- tests/documentation/test_files/DocumentationStyleBear/good_file3.py.test
DocumentationStyleBear now checks for blankline
before and after the docstring and fixes them.
Closes https://github.com/coala/coala/issues/4200
them. …
> DocumentationStyleBear: Add blankline check

- tests/general/URLBearTest.py
This is to avoid the test from passing when
self.check_prerequisites returns
'you are not connected to the internet'.
Test will pass only if True is returned.
Closes https://github.com/coala/coala-bears/issues/1998
them.
After you …
> URLBearTest: Improve self.assertTrue() statement

- bears/python/PythonPackageInitBear.py
Moved class level doc string into `run` method so
that coala gets correct metadata.
Closes https://github.com/coala/coala-bears/issues/1500
them.
When …
> PythonPackageInitBear: Move doc string into 'run'

- bears/general/URLBear.py
- tests/general/URLBearTest.py
Add regex for percentage-encoded URls like
https://img.shields.io/badge/Maintained%3F-yes-green.svg
Fixes https://github.com/coala/coala-bears/issues/1290
them. …
> URLBear: Regex for percentage-encoded URLs

- bears/python/requirements/PySafetyBear.py
- tests/python/requirements/PySafetyBearTest.py
`KeyError` raises because in `insecure_full.json` the `description` key has been replaced with `advisory`
As `pyupio` organisation updated their `insecure_fuul.json` and replaced `dictionary` key with `advisory` key in their `safety` repo also its a live json. First I fetched the `advisory` key form  #`insecure_full.json` in `PySafetyBear.py` and  changed all the `description` key with `advisory`  key in `PySafetyBearTest.py`, it will remove the `keyError`
Fixes https://github.com/coala/coala-bears/issues/2085
> PySafetyBear.py: PySafetyBear fail due to KEYERROR

- bears/vcs/git/GitCommitBear.py
- tests/vcs/git/GitCommitBearTest.py
The bear raised an exception when only the shortlog was included
in the commit message. This commit is meant to fix this bug.
Fixes https://github.com/coala/coala-bears/issues/2031
> GitCommitBear: Fix behaviour for empty body

- bears/css/CSSCombBear.py
- tests/css/CSSCombBearTest.py
Added ``space-before-opening-brace`` in CSSCombBear.py
and updated test accordingly.
Closes https://github.com/coala/coala-bears/issues/2083
> CSSCombBear.py: Add use_space_before_opening_brace

- bears/js/HappinessLintBear.py
- tests/js/HappinessLintBearTest.py
Check the of use_spaces for HappinessLintBear
as it requires tabbed indentation.
Closes https://github.com/coala/coala-bears/issues/1754
them.
When …
> HappinessLintBear: Throw exception when use_spaces

- bears/php/PHPCodeSnifferBear.py
- tests/php/PHPCodeSnifferBearTest.py
Adds and sets `absolute_line_length` to '0'.So as to disable two kinds
of errors.
Closes https://github.com/coala/coala-bears/issues/1950
them.
When …
> PHPCodeSnifferBear: Disable two kinds of error

- .ci/generate_bear_requirements.py
- bear-requirements.txt
- bears/gettext/DennisBear.py
Dennis library was updated to 0.9 and it contains the fix for https://github.com/willkg/dennis/issues/91.
This PR reverts https://github.com/coala/coala-bears/pull/1282 and updates dennis to 0.9 to solve #1284
> Update dennis to 0.9

- bears/documentation/DocumentationStyleBear.py
Since the parameters were specified incorrectly
in DocumentationStyleBear.py, they were changed
to implement correct indentation.
Fixes https://github.com/coala/coala-bears/issues/1941
them.
After you submit your pull request, **DO …
> DocumentationStyleBear: changed docstring format

- .ci/check_unsupported.sh
- .ci/deps.coala-bears.sh
- .travis.yml
The unsupported check was previously a hack inside the main
Travis CI `script` block, requiring many workarounds
throughout the .travis.yml.
Travis CI now supports custom `script` blocks for each build
matrix entry, which allows the logic to be moved to an
external and more clear script.
In addition, all of the installation steps have been
removed, making these jobs much faster to complete.
Closes https://github.com/coala/coala-bears/issues/2182
them.
individually.* It is …
> .travis.yml: Move unsupported check to a script

- .ci/deps.opam.sh
Infer compilation fails when using easy-format v1.3.0
Fixes https://github.com/coala/coala-bears/issues/2059
> .ci/deps.opam.sh: Pin easy-format to v1.2.0

- bear-requirements.txt
- bears/hypertext/HTMLLintBear.py
Update `html-linter` from version `0.3.0` to `0.4.0`.
Closes https://github.com/coala/coala-bears/issues/2004
> HTMLLintBear.py: Update `html-linter`

- bears/apertium/ApertiumLintBear.py
Changed the words `consits` -> `consists` and `Inconsitency`-> `Inconsistency`.
> ApertiumLintBear: Fix typos

- bears/c_languages/CPPCheckBear.py
- tests/c_languages/CPPCheckBearTest.py
- tests/c_languages/cppcheck_test_files/bad_file.cpp
- tests/c_languages/cppcheck_test_files/good_file.cpp
- tests/c_languages/cppcheck_test_files/warn_file.cpp
It solves the following problem #2078 
>Let's say I have a function f, defined in f.cpp and used in g.cpp. If I run cppcheck just on f.cpp, it will tell me [f.cpp:1]: (style) The function 'f' is never used.. If I run cppcheck on the whole directory, that message disappears, because it seems that the function is being used after all. However, in coala, these messages also appear, because, presumably, coala runs cppcheck on each individual file. Can I tell it to run on the whole directory?
> CPPCheckBear.py: Make CPPCheckBear a GlobalBear

- docs-requirements.txt
Change the doc-requirements to build the
circle-ci break.
Fixes https://github.com/coala/coala-bears/issues/2223
EDIT by @Makman2:
Closes --> Fixes (so it's consistent with the commit)
> docs-requirements: build break

- bears/documentation/DocumentationStyleBear.py
- tests/documentation/DocumentationStyleBearTest.py
Add use_spaces param in DocumentationStyleBear.
Closes https://github.com/coala/coala-bears/issues/1834
them. …
> DocumentationStyleBear: Add use_spaces param

- bears/general/LineLengthBear.py
- bears/general/SpaceConsistencyBear.py
SpacingHelper.replace_tabs_with_spaces is a less efficient
implementation of string.expandtabs(), and should be deprecated.
> bears/general: Use string.expandtabs()

- bears/c_languages/CPPLintBear.py
- tests/c_languages/CPPLintBearTest.py
Add infinite line length feature when
max_line_length is zero.
Closes https://github.com/coala/coala-bears/issues/1620
them. …
> CPPLintBear: Add infinite line length

- .travis.yml
Change `sudo: required` to `sudo: enabled` in .travis.yml file
Fixes #2212
them. …
> .travis.yml: Use sudo enabled infrastructure

- bears/jinja2/Jinja2Bear.py
- tests/jinja2/Jinja2BearTest.py
This adds support for whitespace control for
statement tags and when trim_blocks are used
with statement or control tags.
Closes https://github.com/coala/coala-bears/issues/2002
> Jinja2Bear: Add support for whitespace control

- tests/python/PycodestyleBearTest.py
Renamed the final test with a similar name to PycodestyleBearCustomLineLengthTest from PycodestyleBearLineLengthTest.
> PycodestyleBearTest.py: Rename last LineLength test

- .travis.yml
The jobs for unsupported platforms 2.7 & 3.3 do not need to run
so frequently, and any breakages are usually related to upstream
dropping support for 2.7 or 3.3, rather than a local problem.
The master builds will break, and usually we'll need to pin
something to get around the problem.  Ultimately, failure to
verify that these old versions fail in a predictable manner
should not prevent us adding new features or dependencies.
Related to https://github.com/coala/coala/issues/4323
up your stuff for …
> .travis.yml: Skip unsupported except on master

- .ci/check_unsupported.sh
pylint installs pytest-runner, and 2.12 creates a version mismatch.
https://github.com/pytest-dev/pytest-runner/issues/40
Closes https://github.com/coala/coala-bears/issues/2361
them. …
> .ci/check_unsupported.sh: Pin pytest-runner

- tests/coffee_script/CoffeeLintBearTest.py
Infinite line length feature for CoffeeLintBear
Sets the max_line_length value equal to Number.MAX_SAFE_INT
value (taken from javascript) in case this parameter is given as 0.
Closes https://github.com/coala/coala-bears/issues/2272
> CoffeeLintBear: Add 0 max_line_length test

- bears/python/requirements/PySafetyBear.py
- tests/python/requirements/PySafetyBearTest.py
PySafetyBear fails to yield the correct message,
as currenlty we are using 0.5.1 version of
``Safety`` and also live data format also changes,
so PySafetyBear ouputting wrong message template,
changes are done accordingly to prevent the
failing of test of  PySafetyBear and display
correct message template.
Closes: https://github.com/coala/coala-bears/issues/2293
> PySafetyBear.py: Yield correct message template

- bears/c_languages/GNUIndentBear.py
- tests/c_languages/GNUIndentBearTest.py
Add infinite line length feature when
max_line_length is zero.
Closes https://github.com/coala/coala-bears/issues/2249
them. …
> GNUIndentBear: Add infinite line length

- tests/python/requirements/PySafetyBearWithoutMockTest.py
- tests/python/requirements/PySafety_test_files/requirement.txt
Created ``PySafetyBearWithoutMockTest.py`` to run
test for ``PySafetyBear`` without using mock.
Closes https://github.com/coala/coala-bears/issues/2102
> Add: Non-mocked test of PySafetyBear

- .ci/deps.sh
- .ci/env_variables.sh
- .ci/tests.sh
- .coafile
This add a `bash` section and `bash`
as default `shell` in `.coafile`.
Closes #2320
them. …
>  .coafile: Add ShellCheckBear

- bears/python/PycodestyleBear.py
pycodestyle added W504 to the default ignore list.
Closes https://github.com/coala/coala-bears/issues/2428
> PycodestyleBear: Add default ignore W504

- bears/js/PrettierLintBear.py
- tests/js/PrettierLintBearTest.py
Fixes https://github.com/coala/coala-bears/issues/2365
them.
instead. …
> PrettierLintBear.py: Fix syntax error regex

- bears/python/RadonBear.py
- tests/python/RadonBearTest.py
Radon specific settings are removed
and replaced with cc_threshold which
is generic to other complexity analysis bears
Closes https://github.com/coala/coala-bears/issues/772
them.
After you submit your pull request, **DO NOT click …
> RadonBear.py: Change bears settings

- bears/xml2/XMLBear.py
XMLBear can apply patches to formatting errors.
So, setting the CAN_FIX value to ``formatting``.
Closes https://github.com/coala/coala-bears/issues/2420
them. …
> XMLBear.py: Add CAN_FIX metadata

- bears/vcs/git/GitCommitBear.py
Removes "end" from double word "end end".
Closes https://github.com/coala/coala-bears/issues/2452
them. …
> GitCommitBear: Removed doubled word 'end end'

- bears/vcs/git/GitCommitBear.py
Increased modularity by delegating the task of selecting issue
regex to another function
Closes https://github.com/coala/coala-bears/issues/2396
them. …
> GitCommitBear: Refactor issue regexes

- .travis.yml
aspcud is needed by OPAM, otherwise it uses its own
internal & much slower resolver, which blows the stack.
Closes https://github.com/coala/coala-bears/issues/2546
them. …
> .travis.yml: Add apt package aspcud

- .travis.yml
- bears/vcs/git/GitCommitBear.py
- tests/vcs/git/GitCommitBearTest.py
This adds a check in GitCommitBear to identify
Github PR merge commits and ignore
all other tests for these commits.
Closes https://github.com/coala/coala-bears/issues/1037
them.
After you submit your pull request, **DO NOT click …
> GitCommitBear: Ignore Github PR merge commits

- bears/general/FilenameBear.py
Don't make `Diff()` if the new name and the old name are same.
Closes https://github.com/coala/coala-bears/issues/2578
them. …
> FilenameBear: Don't make diff if changes are same

- tests/general/InvalidLinkBearTest.py
Match the expected result with the actual result
in `test_redirect_threshold()` by adding `diffs` argument.
Closes https://github.com/coala/coala-bears/issues/2571
them. …
> InvalidLinkBearTest: Fix test_redirect_threshold

- tests/general/FilenameBearTest.py
Match several testcases in `FilenameBearTest` with the actual
result, especially for the expected `Result` objects that
its `diffs` argument was forgotten.
Closes https://github.com/coala/coala-bears/issues/2564
them.
After you …
> FilenameBearTest: Fix testcases

- bears/c_languages/ClangComplexityBear.py
This fixes AttributeError by replacing previously removed
function of `SourceRange` with `sourcerange_from_clang_range`
function.
Fixes https://github.com/coala/coala-bears/issues/2570
them.
After you submit your pull request, **DO …
> ClangComplexityBear: Fix SourceRange AttributeError

- .travis.yml
This makes Python 3.6 the sentinel job,
so it runs by itself initially and causes
all other jobs to be cancelled if it fails.
them. …
> .travis.yml: Add sentinel job

- tests/general/TextLintBearTest.py
- tests/general/textlint_test_files/bad_alex_no_dead_link.md
httpstat.us and httpbin.org have repeatedly been
causing failures in tests for days at a time.
The Google Teapot is a reliable error page.
Closes https://github.com/coala/coala-bears/issues/2588
them. …
> TextLintBearTest: Replace httpstat.us with Google

- .ci/generate_bear_requirements.py
- .moban.dt/bears-test-requirements.txt.jj2
- .moban.yaml
- .travis.yml
- bear-requirements.yaml
- test-requirements.txt
TODO: break into commits.
This commits updates the script to use ruamel.yaml
which is better fork of PyYaml.
Add Update and Check mode for diffing and updating
Bear-Requirments yaml.
Closes https://github.com/coala/coala-bears/issues/2444
them.
pass on every …
> .ci/generate_bear_requirements: Changes

- bears/python/requirements/PySafetyBear.py
This fixes the typo and changes it from parseable --> parsable
Fixes https://github.com/coala/coala-bears/issues/2629
them. …
> PySafetyBear.py: Fix comment typo

- Gemfile
- bear-requirements.yaml
- bears/ruby/RubyFastererBear.py
- tests/ruby/RubyFastererBearTest.py
- tests/ruby/fasterer_test_files/module_eval.rb
- tests/ruby/fasterer_test_files/sort_vs_sort_by.rb
This adds a `Local Bear` for `Ruby`, wrapping
`fasterer`.
Closes https://github.com/coala/coala-bears/issues/444
> RubyFastererBear.py: Add `fasterer`

- bears/c_languages/ClangBear.py
Variable name range renamed to clang_range.
Fixes https://github.com/coala/coala-bears/issues/2585
them. …
> ClangBear.py: Rename variable range

- bears/vcs/git/CISkipInspectBear.py
- tests/vcs/git/CISkipInspectBearTest.py
This bear inspects git commits that
disable CI build.
Closes https://github.com/coala/coala-bears/issues/1976
them. …
> CISkipInspectBear.py: Bear to inspect commits that disable CI builds

- .ci/check_unsupported.sh
- bear-requirements.txt
- bear-requirements.yaml
- bears/shell/BashateBear.py
- tests/shell/BashateBearTest.py
Bear that uses bashate linter.
Closes https://github.com/coala/coala-bears/issues/2226
them. …
> BashateBear.py: Add a new lint bear

- bears/jinja2/Jinja2Bear.py
- tests/jinja2/Jinja2BearTest.py
This enables the end of block to not have comment.
However by default it would check for the trailing comment
But the behavior can be changed by the user explicitly.
Closes https://github.com/coala/coala-bears/issues/2659
them. …
> Jinja2Bear: Disable the need of trailing comment

- .ci/check_moban.sh
- .ci/check_unsupported.sh
- .moban.yaml
- bears/__init__.py
- setup.cfg
- tests/coalaBearTest.py
Closes https://github.com/coala/coala-bears/issues/2611
Closes https://github.com/coala/coala-bears/issues/2488
> Python minimum version 3.4.4

- .travis.yml
The Python 3.6 job is failing.
Remove it until it is fixed, so that Travis checks
can be required again.
Related to https://github.com/coala/coala-bears/issues/2664
them. …
> .travis.yml: Remove Python 3.6

- tests/swift/TailorBearTest.py
- tests/typescript/TSLintBearTest.py
Ensures that name of tests are consistent with other test modules
that use verify_local_bear
Closes https://github.com/coala/coala-bears/issues/1733
> TailorBearTest.py & TSLintBearTest.py : Change test variables name

- .travis.yml
closes #2453 
Removed `CIRCLE_NODE_INDEX=-1` from `.travis.yml`
> .travis.yml : removed CIRCLE_NODE_INDEX=-1 

- bears/python/PEP8Bear.py
Change in the docstring indentations in PEP8Bear.py
according to reStructured format supported by
Sphinx 1.5.6 to make the docstring parameters more visible.
Closes https://github.com/coala/coala-bears/issues/2437
them.
After you …
> PEP8Bear.py: Change the docstring Indentation

- bears/general/IndentationBear.py
This fixes the typo and changes it from
ofSourceRanges --> of SourceRanges.
Fixes https://github.com/coala/coala-bears/issues/2718
them.
When asked …
> IndentationBear.py: Fix docstring typo

- bears/c_languages/ArtisticStyleBear.py
- bears/c_languages/CPPCheckBear.py
- bears/c_languages/CPPCleanBear.py
- bears/c_languages/CPPLintBear.py
- bears/c_languages/CSecurityBear.py
- bears/c_languages/ClangBear.py
- bears/c_languages/GNUIndentBear.py
To have a standard naming convention for language
names so that C++ and CPP are treated as same language.
Closes https://github.com/coala/coala-bears/issues/2715
them.
After you submit your pull request, **DO NOT click the 'Update …
> Change C++ to CPP at bears language

- bears/python/PEP8NotebookBear.py
- tests/python/PEP8NotebookBearTest.py
The max_line_length when 0 acts as infinite.
Closes https://github.com/coala/coala-bears/issues/2443
them. …
> PEP8NotebookBear: Add infinite length feature

- bears/js/JSONFormatBear.py
- tests/js/JSONFormatBearTest.py
The max_line_length for JSON is infinity by default.
It can be modified if a user is sure about the line length.
Closes https://github.com/coala/coala-bears/issues/2743
them. …
> JSONFormatBear.py: Implement max_line_length

- bears/vcs/CommitBear.py
- tests/vcs/git/GitCommitBearTest.py
- tests/vcs/mercurial/HgCommitBearTest.py
Check if commit message uses 'https' rather than 'http' to automatically close the referenced issue for GitHub and GitLab. Yield host to user if error is caught.
Closes https://github.com/coala/coala-bears/issues/2683
Closes https://github.com/coala/coala-bears/issues/2722
> CommitBear.py: Check proper use of `https` when referencing issues

- bear-languages.yaml
- bears/python/PyStringConcatBear.py
- tests/python/PyStringConcatBearTest.py
Detect use of explicit string concatenation in Python.
The bear checks if a line ends in a `+` and if so checks if the following line starts with a string enclosing character (', ", `).
Closes https://github.com/coala/coala-bears/issues/2434
> PyStringConcatBear.py: Add Py string concat bear

- .nocover.yaml
- bears/js/JSComplexityBear.py
- bears/python/PycodestyleBear.py
- bears/scss/SASSLintBear.py
- setup.cfg
Depends on https://github.com/coala/coala-bears/pull/2658 which in turn depends on https://github.com/coala/coala-bears/pull/2758
> Backwards compatibility for process_output handling empty linter results

- tests/general/TextLintBearTest.py
- tests/general/textlint_test_files/bad_alex_no_dead_link.md
The test data for test_bad_alex_no_dead_link was causing
a error about gender, which was unnecessary in this test.
The underlying error has changed slightly in newer versions
of the linter, so removing the test case allows the bear
to pass tests on a wider array of linter versions.
Closes https://github.com/coala/coala-bears/issues/2777
them.
our bot will still report the issues for the previous …
> TextLintBearTest: Remove unnecessary result

- bear-requirements.yaml
- bears/typescript/TSLintBear.py
- package.json
- tests/general/TextLintBearTest.py
- tests/general/textlint_test_files/bad_alex_no_dead_link.md
- tests/typescript/TSLintBearTest.py
- tests/typescript/test_files/tslint-single.json
Sits on top of https://github.com/coala/coala-bears/issues/2778
> Support Tslint 5

- bears/general/HTTPSBear.py
- tests/general/HTTPSBearTest.py
add test for RequestException
Closes https://github.com/coala/coala-bears/issues/2768
them. …
> HTTPSBear: Remove use of generic no cover

- bears/vcs/CommitBear.py
Fix coverage drop by rolling back nltk to 3.3
Fixes https://github.com/coala/coala-bears/issues/2788
nltk 3.4 was  released on the 17th. The coverage drop happened with https://github.com/coala/coala-bears/pull/2786 which was merged on Nov 17th. On my machine, using nltk 3.3 brings back coverage for 70 -> exit.
Line 70 is setting a lambda for `logger`, which would be passed to `redirect_stdout`. On the subsequent lines, nltk is called. Perhaps there are some changes in nltk 3.4 that broke this. 
I spent a couple of hours looking at the tests and couldn't find anything else that could have caused the coverage drop. I believe this is the likely culprit. 
defined like we require is a hard task and takes some …
> Fix CommitBear coverage drop

- bears/vcs/git/GitRevertInspectBear.py
- tests/vcs/git/GitRevertInspectBearTest.py
Add test case that that mocks an error. 
Closes https://github.com/coala/coala-bears/issues/2774
them. …
> GitRevertInspectBear: Remove use of no cover

- bears/js/ESLintBear.py
- tests/js/ESLintBearTest.py
This removes the use of `#pragma: no cover`
in ESLintBear.
Closes https://github.com/coala/coala-bears/issues/2770
them. …
> ESLintBear: Remove use of generic no cover

- .ci/appveyor.yml
- bears/configfiles/PuppetLintBear.py
- bears/haml/HAMLLintBear.py
- bears/ruby/RubySecurityBear.py
- bears/ruby/RubySmellBear.py
- bears/scss/SCSSLintBear.py
- bears/yaml/TravisLintBear.py
Added commands to install ruby gems in appveyor
so that it can perform tests for the bears that
use ruby gems.
Fixes https://github.com/coala/coala-bears/issues/1305
> Install Ruby gems in AppVeyor

- bears/general/URLHeadBear.py
- tests/general/URLHeadBearTest.py
Changed URL that checks if client is connected to the internet or not
from Google's IP address 216.58.218.174
to DNS IP owned by Cloudfare 1.1.1.1
Fixes https://github.com/coala/coala-bears/issues/2833
them.
After you submit your …
> URLHeadBear.py: Change connection check URL

- bears/c_languages/codeclone_detection/ClangCountingConditions.py
- bears/vcs/git/GitCommitBear.py
W605 is a warning for invalid escape sequences.
In python 3.6, Unknown escapes consisting of `\` and an ASCII letter in regular expressions will
cause an warning.In the upcoming python versions this would be treated as an error.
Owing to it pycodestyle have added this check for future Python versions.
The alternative way to escape special characters now is to append a extra `\` infront of the
sequences. Escape the characters by double backticks.
Fixes https://github.com/coala/coala-bears/issues/2760
for you to learn this. Just drop us a message and we'll take care of …
> CI: Fix Pycodestyle warning W605

- tests/general/TextLintBearTest.py
This typo fix makes the Travis CI build pass
that was originally failing due to
an assertion failure in TextLintBear.
Fixes https://github.com/coala/coala-bears/issues/2851
them.
After you submit your pull request, **DO NOT click …
> TextLintBearTest.py: Fix assertion typo

- .ci/check_setuptools.py
- .ci/check_unsupported.sh
- .moban.yaml
- .travis.yml
Depends on https://github.com/coala/coala-bears/pull/2612
>  .moban.yaml: Add CI check scripts

- bears/python/requirements/PySafetyBear.py
- tests/python/requirements/PySafetyBearTest.py
The newer Safety package(v1.8.5) now adds the
functionality to support proxies which the Requests
package of Python uses.
The above functionality by Safety has been provided
by adding an extra positional argument called `proxy`
in the `saftey.check()` function. This caused the
TypeError in the previous version of Safety,due to
mismatch of number of positional argument
Closes https://github.com/coala/coala-bears/issues/2857
them.
individually.* It is not sufficient to have …
> PySafetyBear.py: Add proxy positional argument

- bears/general/LineContinuationBear.py
- tests/general/LineContinuationBearTest.py
Add condition in LineContinuationBear to ignore backslashes in
`from` imports inside doctest.
Closes https://github.com/coala/coala-bears/issues/2806
them. …
> LineContinuationBear: Disable if `from` in doctest

- bear-requirements.txt
- bear-requirements.yaml
- bears/rest/reSTLintBear.py
This adds support for Sphinx prolog and epilog and other new
features by changing restructuredtext-lint version from '1.0.0'
to '1.0' in the files reSTLintBear.py, bear-requirements.txt
and bear-requirements.yaml. This is done by ensuring that
upgrading to versions '1.1.x' and '1.2.x' is also allowed.
Closes https://github.com/coala/coala-bears/issues/1954
them.
our bot will still report the issues for …
> reSTLintBear.py: Change rst_lint version

- bear-requirements.txt
- bear-requirements.yaml
- bears/c_languages/codeclone_detection/ClangFunctionDifferenceBear.py
The official [munkres](https://github.com/bmc/munkres) now supports Python3, so
we don't need to use [munkres3](https://github.com/datapublica/munkres).
Closes #2871
> Replace dep munkres3 with munkres

- .ci/generate_bear_metadata.py
- bear-metadata.yaml
- bear-requirements.txt
- bear-requirements.yaml
- bears/python/YapfBear.py
- tests/python/YapfBearTest.py
Modify test_allow_multiline_lambdas to be
version specific.
Closes https://github.com/coala/coala-bears/issues/2873
Change "overrides" filename from
package-manager-requirements.yaml to pm-requirements.yaml
Fixes https://github.com/coala/coala-bears/issues/2936
them.
> Add support for yapf>=0.21.0<0.27.0 and fix filename in .ci/generate_bear_metadata.py

- .ci/deps.java.sh
- .ci/generate_bear_metadata.py
- .ci/generate_coverage_thresholds.py
- .ci/get_tests.py
- .moban.yaml
- Fudgefile
- bear-metadata.yaml
- bear-requirements.txt
- bear-requirements.yaml
- bears/apertium/ApertiumLintBear.py
- bears/general/CPDBear.py
- bears/java/JavaPMDBear.py
- tests/general/CPDBearTest.py
- tests/java/JavaPMDBearTest.py
- tests/xml2/XMLBearTest.py
- tox.ini
> Fix pmd bears on Windows

- bears/hypertext/HTMLLintBear.py
This restores prior behaviour.
Fixes https://github.com/coala/coala-bears/issues/2949
> HTMLLintBear: Enable use_spaces by default

- bears/general/IndentationBear.py
- tests/general/IndentationBearTest.py
This adds a new implementation to ignore all
the doc comments from IndentationBear since
doc comments are not supossed to follow indentation.
Closes https://github.com/coala/coala-bears/issues/644
them. …
> IndentationBear: Ignore doc comments
